import { expect, test } from '@playwright/test'
import { pickStudioOptionByValue, readStudioOptions } from './helpers/studioSelect'

test('archive content reveals and route changes leave one active page', async ({ page }) => {
  await page.goto('/style')
  await expect(page.locator('.mood-grid[data-reveal]')).toHaveClass(/revealed/)
  await page.locator('.nav-more-trigger').click()
  await page.getByRole('dialog', { name: '更多页面' }).getByRole('link', { name: '我的作品', exact: true }).click()
  await expect(page).toHaveURL(/\/gallery$/)
  await expect(page.locator('main h1')).toHaveCount(1)
  await expect(page.getByRole('heading', { level: 1, name: '我的作品', exact: true })).toBeVisible()
  await expect(page.locator('.gallery-toolbar[data-reveal]')).toHaveClass(/revealed/)
})

test('character directory filters by franchise and opens matching details', async ({ page }) => {
  await page.goto('/character?character=nene')
  const directory = page.getByRole('complementary', { name: '角色目录' })
  await expect(directory.locator('.directory-item').first()).toBeVisible()
  const total = await directory.locator('.directory-item').count()
  expect(total).toBeGreaterThanOrEqual(45)
  const search = directory.getByRole('searchbox', { name: '搜索角色或作品' })
  await search.fill('凯尔希')
  await directory.locator('.directory-item').first().click()
  await expect(page.locator('.character-name')).toHaveText('凯尔希')
  await expect(page.locator('.character-hero')).toBeVisible()
  await search.fill('')
  const seriesTrigger = directory.getByLabel('筛选角色系列')
  const arknightsSeries = (await readStudioOptions(seriesTrigger)).find(option => option.label.startsWith('明日方舟 ·'))
  expect(arknightsSeries).toBeDefined()
  await pickStudioOptionByValue(seriesTrigger, arknightsSeries!.value)
  const arknights = await directory.locator('.directory-item').count()
  expect(arknights).toBeGreaterThanOrEqual(13)
  expect(arknights).toBeLessThan(total)
  await pickStudioOptionByValue(seriesTrigger, '')
  await search.fill('Fate')
  await expect.poll(() => directory.locator('.directory-item').count()).toBeGreaterThanOrEqual(3)
  expect(await directory.locator('.directory-item').count()).toBeLessThan(total)
  await directory.getByRole('button', { name: '清除筛选' }).click()
  await expect(directory.locator('.directory-item')).toHaveCount(total)
})

for (const theme of ['light', 'dark']) {
  if (theme === 'dark') test(`character bookshelf preserves search and selection through profile history ${theme}`, async ({ page }) => {
    await page.addInitScript(value => localStorage.setItem('aics_theme', value), theme)
    await page.goto('/character')
    const shelf = page.getByRole('region', { name: '角色作品书架' })
    await expect(shelf).toBeVisible()
    await expect(page.locator('.character-hero')).toHaveCount(0)
    await expect(page.locator('main h1')).toHaveCount(1)
    const search = shelf.getByRole('searchbox', { name: '搜索角色、别名或作品' })
    await search.fill('芙宁娜')
    await expect(shelf.locator('.bookshelf-character')).toHaveCount(1)
    await search.press('Enter')
    await expect(page).toHaveURL(/character=furina/)
    await expect(page.locator('.character-name')).toHaveText('芙宁娜')
    await page.goBack()
    await expect(shelf).toBeVisible()
    await expect(search).toHaveValue('芙宁娜')
    await expect(shelf.locator('[data-character="furina"]')).toBeFocused()
    await page.goForward()
    await expect(page.locator('.character-name')).toHaveText('芙宁娜')
    await page.getByRole('button', { name: '返回作品书架', exact: true }).click()
    await expect(shelf).toBeVisible()
    await expect(search).toHaveValue('芙宁娜')
    await shelf.getByRole('button', { name: '作品书架', exact: true }).click()
    const work = shelf.locator('[data-franchise="Arknights"]')
    await work.click()
    await expect(shelf.getByRole('heading', { name: '明日方舟', exact: true })).toBeFocused()
    await expect(shelf.locator('.bookshelf-character').first()).toBeVisible()
    await shelf.getByRole('button', { name: '返回书架', exact: true }).click()
    await expect(work).toBeFocused()
  })
}
