import { expect, test } from '@playwright/test'
import { textContrast } from './helpers/contrast'

for (const theme of ['dark', 'light']) {
  test(`global search finds the oldest of 10000 works ${theme}`, async ({ page }) => {
    await page.addInitScript(theme => localStorage.setItem('aics_theme', theme), theme)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/')
    await page.evaluate(async () => {
      await new Promise<void>((resolve, reject) => {
        const request = indexedDB.open('aics_kv_store', 1)
        request.onupgradeneeded = () => request.result.createObjectStore('kv', { keyPath: 'key' })
        request.onerror = () => reject(request.error)
        request.onsuccess = () => {
          const db = request.result, tx = db.transaction('kv', 'readwrite')
          tx.objectStore('kv').put({ key: 'aics_pb_history', value: Array.from({ length: 10000 }, (_, i) => ({ id: i + 1, timestamp: i + 1, sceneTitle: i === 0 ? 'oldest-neutral-sentinel' : 'neutral' })) })
          tx.oncomplete = () => { db.close(); resolve() }
          tx.onerror = () => reject(tx.error)
        }
      })
    })
    const start = Date.now()
    await page.keyboard.press('Control+k')
    const input = page.getByRole('searchbox', { name: '搜索场景、作品或页面' })
    await input.fill('oldest-neutral-sentinel')
    await expect(page.getByRole('option', { name: /oldest-neutral-sentinel/ })).toBeVisible()
    console.log(JSON.stringify({ theme, search10000Ms: Date.now() - start }))
    await page.screenshot({ path: `runtime/audit-011/b4-${theme}.png` })
    await input.press('Enter')
    await expect(page).toHaveURL(/regen=1(?:&|$)/)
  })
  test(`reset profile-only content with keyboard ${theme}`, async ({ page, context }) => {
    await page.addInitScript(theme => localStorage.setItem('aics_theme', theme), theme)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/')
    await page.evaluate(theme => {
      localStorage.setItem('aics_theme', theme)
      localStorage.setItem('aics_user_profile_v1', JSON.stringify({ callName: 'neutral', note: 'neutral' }))
      localStorage.setItem('aics_chat_draft_v1:retired', '"neutral"')
    }, theme)
    await page.reload()
    await page.goto('/chat')
    const other = await context.newPage()
    await other.goto('/chat')
    await other.locator('.chat-input').fill('neutral-late-draft')
    await page.locator('.chat-actions').getByRole('button', { name: '更多' }).click()
    await page.getByRole('menuitem', { name: '清空聊天内容与个人档案', exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
    const confirm = page.getByRole('button', { name: '清空聊天内容', exact: true })
    await expect(confirm).toBeVisible()
    await expect(page.getByRole('button', { name: '取消', exact: true })).toBeFocused()
    expect(await page.locator('.confirm-message').evaluate(textContrast, null)).toBeGreaterThanOrEqual(4.5)
    expect(await confirm.evaluate(textContrast, null)).toBeGreaterThanOrEqual(4.5)
    await page.screenshot({ path: `runtime/audit-011/b2-confirm-${theme}.png`, fullPage: true })
    await page.keyboard.press('Escape')
    expect(await page.evaluate(() => localStorage.getItem('aics_user_profile_v1'))).toContain('neutral')
    await page.locator('.chat-actions').getByRole('button', { name: '更多' }).click()
    await page.getByRole('menuitem', { name: '清空聊天内容与个人档案', exact: true }).click()
    await confirm.focus()
    await page.keyboard.press('Enter')
    await expect(page.getByText('本机聊天内容与个人档案已清空；连接和偏好已保留。')).toBeVisible()
    expect(await page.evaluate(() => localStorage.getItem('aics_user_profile_v1'))).toBeNull()
    expect(await page.evaluate(() => localStorage.getItem('aics_chat_draft_v1:retired'))).toBeNull()
    await expect(other.locator('.chat-input')).toHaveValue('')
    await other.reload()
    await expect(other.locator('.chat-input')).toHaveValue('')
    await other.locator('.chat-input').fill('new-after-clear')
    await expect.poll(() => other.evaluate(() => localStorage.getItem('aics_chat_draft_v1:nene'))).toContain('new-after-clear')
    await other.close()
    await page.reload()
    expect(await page.evaluate(() => localStorage.getItem('aics_user_profile_v1'))).toBeNull()
  })
  test(`future chat remains byte-identical after navigation and reload ${theme}`, async ({ page, context }) => {
    const original = '{ "version": 999, "sentinel": "neutral-future", "histories": {"raiden_shogun": []} }'
    await page.addInitScript(theme => localStorage.setItem('aics_theme', theme), theme)
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.goto('/')
    await page.evaluate(({ original, theme }) => {
      localStorage.setItem('aics_chat_v1', original)
      localStorage.setItem('aics_theme', theme)
    }, { original, theme })
    await page.reload()
    await page.goto('/chat')
    await expect(page.getByText(/聊天数据版本不兼容或已损坏/).first()).toBeVisible()
    await page.screenshot({ path: `runtime/audit-011/b1-${theme}.png`, fullPage: true })
    const second = await context.newPage()
    await second.goto('/chat?character=natsume')
    await page.goto('/settings')
    await page.reload()
    await page.goto('/chat')
    await page.reload()
    expect(await page.evaluate(() => localStorage.getItem('aics_chat_v1'))).toBe(original)
    expect(await page.evaluate(() => localStorage.getItem('aics_retired_companion_chat_v1'))).toBeNull()
    await second.close()
  })
}
