import { expect, test } from '@playwright/test'
import { textContrast } from './helpers/contrast'

for (const theme of ['light', 'dark']) for (const width of [1440, 390]) {
  test(`tabs and data tools preserve focus ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height:844 })
    await page.emulateMedia({ reducedMotion:'reduce' })
    await page.addInitScript(theme => {
      localStorage.setItem('aics_theme', theme)
      localStorage.setItem('aics_pb_director_mode', 'pro')
    }, theme)
    await page.route(/^http:\/\/[^/]+\/api\//, route => route.fulfill({ json:{ ok:true, online:false, models:[], loras:[], styleLoras:[] } }))
    await page.goto('/prompt-builder')
    const render = page.getByRole('tab', { name:'生成', exact:true })
    await render.click()
    await render.press('ArrowRight')
    const style = page.getByRole('tab', { name:'画面', exact:true })
    await expect(style).toBeFocused()
    await expect(style).toHaveAttribute('aria-selected', 'true')
    await expect(style).toHaveAttribute('aria-controls', 'inspector-style')
    await expect(page.locator('#inspector-style')).toHaveAttribute('aria-labelledby', 'inspector-tab-style')
    await expect(page.locator('.inspector-section:visible')).toHaveCount(1)
    const list = page.getByRole('tablist', { name:'参数分类' })
    expect(await style.evaluate(textContrast)).toBeGreaterThanOrEqual(4.5)
    await style.press('End')
    const delivery = page.getByRole('tab', { name:'任务', exact:true })
    await expect(delivery).toBeFocused()
    await delivery.press('Home')
    await expect(render).toBeFocused()
    await render.press('ArrowLeft')
    await expect(delivery).toBeFocused()
    await page.getByRole('tab', { name:'提示词', exact:true }).click()
    await expect(page.locator('#promptMonitor')).toBeVisible()
    await page.screenshot({ path:info.outputPath(`tabs-${theme}-${width}.png`) })
    await page.getByRole('button', { name:'场景模式', exact:true }).click()
    await expect(list).toBeHidden()
    await expect(page.getByRole('tabpanel')).toHaveCount(0)
    await page.getByRole('button', { name:'专家模式', exact:true }).click()
    await expect(page.getByRole('tab', { name:'提示词', exact:true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.locator('#promptMonitor')).toBeVisible()

    const trigger = page.locator('.utility-trigger')
    const menu = page.getByRole('dialog', { name:'数据工具', exact:true })
    await trigger.click()
    await expect(menu).toBeVisible()
    const box = (await menu.boundingBox())!
    expect(box.x).toBeGreaterThanOrEqual(0)
    expect(box.x + box.width).toBeLessThanOrEqual(width)
    expect(box.y + box.height).toBeLessThanOrEqual(844)
    expect(await menu.locator('.utility-heading').evaluate(textContrast)).toBeGreaterThanOrEqual(4.5)
    await page.screenshot({ path:info.outputPath(`tools-${theme}-${width}.png`) })
    await page.keyboard.press('Escape')
    await expect(menu).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await trigger.press('Enter')
    await expect(menu).toBeVisible()
    // Preview a neutral backup; cancel without importing any records or images.
    await page.locator('.pb-backup-file-input').setInputFiles({ name:'ui-preview.json', mimeType:'application/json', buffer:Buffer.from(JSON.stringify({
      app:'ai-cg-studio', schemaVersion:2, data:{ history:[{ id:'ui-preview-record', sceneTitle:'预览夹具' }], projects:[], settings:{} }, images:[],
    })) })
    const preview = page.getByRole('dialog', { name:'从备份恢复', exact:true })
    await expect(preview).toBeVisible()
    await expect(menu).toHaveCount(0)
    await expect(preview.getByRole('button', { name:'取消', exact:true })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(preview).toHaveCount(0)
    await expect(trigger).toBeFocused()
    await expect(page.locator('body')).not.toHaveClass(/overlay-open/)
  })
}
