const { CONTRACT_ISOLATION }: typeof import('./contract-test-policy') = require('./contract-test-policy');
'use strict';

const QUALITY_TEST_SUITES = Object.freeze({
  check: Object.freeze([
    'test-repo-hygiene.js',
    'test-repo-hygiene-contract.js',
    'test-bundle-budget.js',
    'test-workflow-runner.js',
    'test-doc-redirects.js',
    'test-desktop-staging.js',
    'test-e2e-ci-split.js',
    'test-page-architecture.js',
    'test-module-boundaries.mjs',
    'test-domain-type-boundaries.js',
    'test-monolith-budget.js',
    'test-runtime-generated.js',
    'test-typescript-build.js',
    'test-typescript-development.js',
    'test-storage-key-hygiene.js',
    'test-style-debt.js',
    'test-bridge-acl.js',
    'test-icon-button-labels.js',
    'test-native-controls.js',
    'test-ux-regressions.js',
  ]),
  unit: Object.freeze([
    'test-reference-shards.js',
    'test-reference-library-merge.js',
    'test-content-sync.js',
    'test-character-reference-profile.js',
    'test-domain-type-boundaries-fixtures.js',
    'test-refactor-boundaries-fixtures.js',
    'test-test-process-pool.js',
    'test-precompress-runner.js',
    'test-workflow-conditions.js',
    'test-runtime-errors.js',
    'test-quality-report.js',
    'test-content-ownership.js',
    'test-content-history.js',
    'test-content-consistency.js',
    'test-content-impact-check.js',
    'test-content-evidence-audit.js',
    'test-content-contract-root.js',
    'test-blueprint-change-plan.js',
    'test-blueprint-write.js',
    'test-reference-audit-root.js',
    'test-scene-rating-diagnostics.js', // 人工 R15 usage 真实隔离写入、受保护字段保持与幂等检查
    'test-anima-session.js',
    'test-api-client.js',
    'test-artwork-persistence-prototype.js',
    'test-workspace-storage.js',
    'test-workspace-client.js',
    'test-workspace-backup.js',
    'test-workspace-migration.js',
    'test-task-runtime.js',
    'test-desktop-workspace-host.js',
    'test-batch-draw.js',
    'test-blink-scheduler.js',
    'test-character-profiles.js',
    'test-chat-storage.js',
    'test-chat-host-config.js',
    'test-companion-behavior.js',
    'test-companion-affection.js',
    'test-companion-vision.js',
    'test-companion-events.js',
    'test-comfy-progress.js',
    'test-comfy-client.js',
    'test-scene-render-contract.js',
    'test-scene-patch.js',
    'test-control-operation.js',
    'test-data-backup.js',
    'test-desktop-native-evidence.js',
    'test-desktop-updates.js',
    'test-desktop-import.js',
    'test-drawing-route.js',
    'test-emotion-runtime.js',
    'test-environment-context.js',
    'test-job-snapshots.js',
    'test-inpaint-scene-candidates.js',
    'test-inpaint-canvas.js',
    'test-live2d-backend.js',
    'test-live2d-native-contract.js',
    'test-live2d-service.js',
    'test-live2d-imports.js',
    'test-live2d-textures.js',
    'test-logger.js',
    'test-logger-retention.js',
    'test-logger-safety.js',
    'test-compare-snapshots.js',
    'test-inpaint-showcase-candidates.js',
    'test-interrogate-merge.js',
    'test-lora-catalog.js',
    'test-manual-review.js',
    'test-mood-tag.js',
    'test-particle-portrait.js',
    'test-prompt-builder-modules.js',
    'test-prompt-compiler.js',
    'test-prompt-corpus.js',
    'test-prompt-policy.js',
    'test-prompt-rewrite-integrity.js',
    'test-quality-prompt-contract.js',
    'test-random-prompt.js',
    'test-popular-content.js',
    'test-content-gate-repairs.js',
    'test-coverage-report.js',
    'test-content-impact.js', // 角色/默认服装、参考声明证据、主题、场景、精选/退役路径、样张及 Git、失败关闭与索引零写入
    'test-delivery-audit.js', // W2 双证据标识比较、文件哈希、HEAD/worktree；隔离 Git 零写入与失败关闭
    'test-delivery-evidence.js',
    'test-delivery-handoff.js',
    'test-delivery-finalize.js',
    'test-generation-workflow-safety.js',
    'test-reference-candidate-workflow.js',
    'test-scene-prose-contract.js',
    'test-quick-create.js',
    'test-resource-manifest.js', // G5 资源清单生成/校验：稳定排序、字节哈希、越界/junction 拒绝、零写入与退出码契约
    'test-resource-pack.js', // G10 离线候选包暂存导出：预览零写入、清单核验复用、目标/junction 拒绝、失败不发布与字节复核
    'test-resource-pack-delta.js', // G13 增量候选包：只复制 added/changed、旧清单结构核验零旧资产访问、delta.json 身份与零差异候选
    'test-resource-pack-verify.js', // G15 增量候选包兼容核验：基线身份/removed 逐项/重建目标/候选字节，零写入与旧资产零访问
    'test-resource-install.js',
    'test-resource-packaging.js',
    'test-resource-install-recovery.js',
    'test-resource-install-edge.js',
    'test-resource-install-resolver.js',
    'test-resource-download.js',
    'test-resource-scheduling.js',
    'test-scene-ux.js',
    'test-scene-write.js',
    'test-scene-change-set.js',
    'test-sd-error.js',
    'test-serial-queue.js',
    'test-service-watchdog.js',
    'test-showcase.js',
    'test-showcase-candidate-contract.js',
    'test-speech-session.js',
    'test-storage-health.js',
    'test-storage-reliability.js',
    'test-storage-repositories.js',
    'test-task-recovery-prototype.js',
    'test-vad-segmenter.js',
    'test-voice-baseline.js',
    'test-voice-profile-contract.js',
    'test-video-prompt-prose.js',
    'test-wav-quality.js',
  ]),
  contract: Object.freeze([
    'test-workspace-routes.js',
    'test-workspace-library-http.js',
    'test-maintenance-recovery.js',
    'test-maintenance-recovery-boundaries.js',
    'test-maintenance-read-barrier.js',
    'test-maintenance-transaction-routes.js',
    'test-resource-gateway.js',
    'test-resource-reference-gateway.js',
    'test-maintenance-blueprint-transaction.js',
    'test-anima-routes.js',
    'test-desktop-tools-route.js',
    'test-generation-routes.js',
    'test-webui-lifecycle.js',
    'test-chat.js',
    'test-control-failure-contract.js',
    'test-gateway-contract.js',
    'test-remote-content.js',
    'test-gateway-token.js',
    'test-http-client.js',
    'test-maintenance.js',
    'test-scene-maintenance-save.js',
    'test-interrogate-routes.js',
    'test-interrogate-engine.js',
    'test-live2d-route.js',
    'test-character-reference-contract.js',
    'test-pinned-scene-prompts.js',
    'test-scene-story-alignment.js',
    'test-sd-runtime.js',
    'test-scene-shard-integrity.js',
    'test-tag-shards.js',
    'test-popular-shard-integrity.js',
    'test-blueprint-shard-integrity.js',
    'test-security.js',
    'test-tunnel-restart.js',
    'test-upstream-health.js',
    'test-precompressed.js',
    'test-video-ai.js',
    'test-video-routes.js',
  ]),
});

interface TestMetadata {
  domain: string; environment: string; parallelSafety: 'isolated' | 'serial' | 'unreviewed';
  resources: readonly string[]; timeoutMs?: number;
}
const QUALITY_TEST_METADATA: Readonly<Record<string, TestMetadata>> = Object.freeze({
  'test-webui-lifecycle.js': { domain:'generation-lifecycle', environment:'node-loopback', parallelSafety:'isolated', resources:['temporary-directory', 'loopback-http', 'process-local-mocks'] },
  'test-logger-safety.js': { domain:'diagnostics', environment:'node', parallelSafety:'isolated', resources:['temporary-directory', 'process-local-mocks'] },
  'test-api-client.js': { domain: 'generation-api', environment: 'node', parallelSafety: 'isolated', resources: ['mock-fetch', 'timers'] },
  'test-module-boundaries.mjs': { domain: 'architecture', environment: 'node', parallelSafety: 'isolated', resources: ['read-only-source'] },
  'test-live2d-renderer-process.mjs': { domain: 'native-renderer', environment: 'windows-gpu', parallelSafety: 'serial', resources: ['isolated-config-profile', 'owned-renderer-processes', 'visible-test-window', 'local-gpu', 'read-only-installed-models'], timeoutMs: 300_000 },
  'test-electron-shell.mjs': { domain: 'desktop-shell-comparison', environment: 'windows-gpu', parallelSafety: 'serial', resources: ['isolated-config-profile-ai', 'owned-runtime-and-renderer-processes', 'visible-test-windows', 'loopback-cdp', 'local-gpu', 'read-only-build-and-models'], timeoutMs: 300_000 },
});
function qualityTestMetadata(file: string): TestMetadata {
  const contract = CONTRACT_ISOLATION[file];
  if (contract) return { domain: 'contract', environment: 'node-loopback', parallelSafety: 'isolated', resources: [contract.fixture] };
  return QUALITY_TEST_METADATA[file] ?? { domain: 'unclassified', environment: 'node', parallelSafety: 'unreviewed', resources: ['unreviewed'] };
}
// Browser and real packaged-Windows probes have separate explicit execution prerequisites.
const QUALITY_EXTERNAL_TESTS = Object.freeze(['test-resource-ui-visual.mjs', 'test-workspace-sidecar.js', 'test-workspace-migration-browser.mjs', 'test-desktop-library-browser.mjs', 'test-task-center-browser.mjs', 'test-live2d-renderer-process.mjs', 'test-electron-shell.mjs']);
export = { QUALITY_TEST_SUITES, QUALITY_TEST_METADATA, QUALITY_EXTERNAL_TESTS, qualityTestMetadata };
