const { CONTRACT_ISOLATION }: typeof import('./contract-test-policy') = require('./contract-test-policy');

// Each file has one execution owner; discovery validation rejects omissions and duplicates.
const QUALITY_TEST_SUITES = Object.freeze({
  // Repository boundaries and test registration.
  check: Object.freeze([
    'test-repo-hygiene.js',
    'test-doc-redirects.js',
    'test-page-architecture.js',
    'test-module-boundaries.mjs',
    'test-domain-type-boundaries.js',
    'test-monolith-budget.js',
    'test-runtime-generated.js',
    'test-storage-key-hygiene.js',
    'test-icon-button-labels.js',
    'test-native-controls.js',
  ]),
  // Current frontend and shared product behavior.
  unit: Object.freeze([
    'test-reference-shards.js',
    'test-runtime-errors.js',
    'test-runtime-experiment-cleanup.js',
    'test-api-client.js',
    'test-batch-draw.js',
    'test-blink-scheduler.js',
    'test-character-profiles.js',
    'test-chat-storage.js',
    'test-companion-behavior.js',
    'test-companion-affection.js',
    'test-companion-vision.js',
    'test-companion-events.js',
    'test-scene-render-contract.js',
    'test-data-backup.js',
    'test-desktop-import.js',
    'test-drawing-route.js',
    'test-emotion-runtime.js',
    'test-environment-context.js',
    'test-inpaint-canvas.js',
    'test-live2d-backend.js',
    'test-lora-catalog.js',
    'test-mood-tag.js',
    'test-prompt-builder-modules.js',
    'test-prompt-compiler.js',
    'test-prompt-corpus.js',
    'test-prompt-policy.js',
    'test-random-prompt.js',
    'test-popular-content.js',
    'test-content-gate-repairs.js',
    'test-quick-create.js',
    'test-scene-ux.js',
    'test-sd-error.js',
    'test-sd-runtime.js',
    'test-speech-session.js',
    'test-storage-health.js',
    'test-storage-reliability.js',
    'test-storage-repositories.js',
    'test-vad-segmenter.js',
    'test-voice-baseline.js',
    'test-wav-quality.js',
  ]),
  // Content and security contracts used by the current product.
  contract: Object.freeze([
    'test-character-reference-contract.js',
    'test-pinned-scene-prompts.js',
    'test-scene-story-alignment.js',
    'test-scene-shard-integrity.js',
    'test-tag-shards.js',
    'test-popular-shard-integrity.js',
    'test-blueprint-shard-integrity.js',
    'test-security.js',
  ]),
  // Build, maintenance and test-runner behavior; selected when its consumers change.
  tooling: Object.freeze([
    'test-repo-hygiene-contract.js',
    'test-bundle-budget.js',
    'test-workflow-runner.js',
    'test-maintenance-recovery.js',
    'test-maintenance-recovery-boundaries.js',
    'test-e2e-ci-split.js',
    'test-typescript-build.js',
    'test-typescript-development.js',
    'test-style-debt.js',
    'test-reference-library-merge.js',
    'test-content-sync.js',
    'test-domain-type-boundaries-fixtures.js',
    'test-refactor-boundaries-fixtures.js',
    'test-test-process-pool.js',
    'test-precompress-runner.js',
    'test-workflow-conditions.js',
    'test-quality-report.js',
    'test-content-ownership.js',
    'test-content-history.js',
    'test-content-consistency.js',
    'test-content-impact-check.js',
    'test-content-evidence-audit.js',
    'test-content-contract-root.js',
    'test-blueprint-change-plan.js',
    'test-blueprint-write.js',
    'test-reference-audit-root.js',
    'test-scene-rating-diagnostics.js',
    'test-scene-patch.js',
    'test-inpaint-scene-candidates.js',
    'test-inpaint-showcase-candidates.js',
    'test-manual-review.js',
    'test-prompt-rewrite-integrity.js',
    'test-quality-prompt-contract.js',
    'test-coverage-report.js',
    'test-content-impact.js',
    'test-generation-workflow-safety.js',
    'test-reference-candidate-workflow.js',
    'test-scene-prose-contract.js',
    'test-scene-write.js',
    'test-scene-change-set.js',
    'test-showcase.js',
    'test-showcase-candidate-contract.js',
  ]),
  // Packaging, installation and delivery evidence; no real device or model calls.
  release: Object.freeze([
    'test-desktop-staging.js',
    'test-desktop-update-path.js',
    'test-bridge-acl.js',
    'test-desktop-deploy-guard.js',
    'test-desktop-native-evidence.js',
    'test-desktop-updates.js',
    'test-delivery-audit.js',
    'test-delivery-evidence.js',
    'test-delivery-handoff.js',
    'test-delivery-finalize.js',
    'test-resource-manifest.js',
    'test-resource-pack.js',
    'test-resource-pack-delta.js',
    'test-resource-pack-verify.js',
    'test-resource-install.js',
    'test-resource-packaging.js',
    'test-offline-release.js',
    'test-model-downloads.js',
    'test-resource-install-recovery.js',
    'test-resource-install-edge.js',
    'test-resource-install-resolver.js',
    'test-resource-download.js',
  ]),
});

interface TestMetadata {
  domain: string; environment: string; parallelSafety: 'isolated' | 'serial' | 'unreviewed';
  resources: readonly string[]; timeoutMs?: number;
}
const QUALITY_TEST_METADATA: Readonly<Record<string, TestMetadata>> = Object.freeze({
  'test-showcase.js': { domain: 'showcase-http-and-tools', environment: 'rust-loopback', parallelSafety: 'isolated', resources: ['temporary-application-and-runtime', 'owned-rust-process', 'mock-upstreams', 'verified-native-image-library'] },
  'test-desktop-deploy-guard.js': { domain: 'desktop-deployment', environment: 'windows', parallelSafety: 'isolated', resources: ['temporary-install-and-config', 'owned-node-fixture'], timeoutMs: 60_000 },
  'test-api-client.js': { domain: 'generation-api', environment: 'node', parallelSafety: 'isolated', resources: ['mock-fetch', 'timers'] },
  'test-module-boundaries.mjs': { domain: 'architecture', environment: 'node', parallelSafety: 'isolated', resources: ['read-only-source'] },
  'test-live2d-renderer-process.mjs': { domain: 'native-renderer', environment: 'windows-gpu', parallelSafety: 'serial', resources: ['isolated-config-profile', 'owned-renderer-processes', 'visible-test-window', 'local-gpu', 'read-only-installed-models'], timeoutMs: 300_000 },
  'test-electron-shell.mjs': { domain: 'desktop-shell-comparison', environment: 'windows-gpu', parallelSafety: 'serial', resources: ['isolated-config-profile-ai', 'owned-runtime-and-renderer-processes', 'visible-test-windows', 'loopback-cdp', 'local-gpu', 'read-only-build-and-models'], timeoutMs: 300_000 },
});
function qualityTestMetadata(file: string): TestMetadata {
  const contract = CONTRACT_ISOLATION[file];
  if (contract) return { domain: 'contract', environment: 'node-loopback', parallelSafety: 'isolated', resources: [contract.fixture] };
  return QUALITY_TEST_METADATA[file] ?? { domain: 'unclassified', environment: 'node', parallelSafety: 'unreviewed', resources: ['unreviewed'] };
}
// Browser and real packaged-Windows probes have separate explicit execution prerequisites.
const QUALITY_EXTERNAL_TESTS = Object.freeze(['test-resource-ui-visual.mjs', 'test-rust-bundle.js', 'test-workspace-migration-browser.mjs', 'test-desktop-library-browser.mjs', 'test-task-center-browser.mjs', 'test-live2d-renderer-process.mjs', 'test-electron-shell.mjs']);
export = { QUALITY_TEST_SUITES, QUALITY_TEST_METADATA, QUALITY_EXTERNAL_TESTS, qualityTestMetadata };
