import type { ArtistStyleOption } from './artistStyles.ts'
import { ARTIST_STYLE_OFFICIAL_OPTIONS } from './artistStyleCatalogOfficial.ts'

export const ARTIST_STYLE_OPTIONS: readonly ArtistStyleOption[] = Object.freeze([
  // ── 电影光影与通透氛围 ──────────────────────────────────────────
  {
    id: 'yoneyama_mai',
    name: 'Yoneyama Mai',
    cnName: '米山舞',
    waiTag: 'yoneyama_mai',
    animaTag: '@yoneyama mai',
    description: '电影感调色、松弛流动线条与强情绪光影',
    masterpiece: '《赛博朋克 边缘行者》ED、《EVA》官方海报、《RADIO EVA》',
    category: 'cinematic',
    verification: 'tag',
    keywords: ['电影感', '光影', '动态', '去塑料感', 'eva', '神仙画风'],
  },
  {
    id: 'rella',
    name: 'Rella',
    cnName: 'Rella',
    waiTag: 'rella',
    animaTag: '@rella',
    description: '梦幻夜景辉光、空灵色彩与电影照明',
    masterpiece: '《初音未来交响乐 (Miku Symphony)》、VOCALOID 官方主视觉',
    category: 'cinematic',
    verification: 'curated',
    keywords: ['星空', '夜景', '梦幻', '水下', '光斑', '初音'],
  },
  {
    id: 'swav',
    name: 'SWAV',
    cnName: 'SWAV',
    waiTag: 'swav',
    animaTag: '@swav',
    description: '高冲击力幻想海报、魔法光照与纵深',
    masterpiece: '《明日方舟》周年大片插画、《少女前线》视觉图',
    category: 'cinematic',
    verification: 'curated',
    keywords: ['纵深', '魔法光', '海报', '空间感', '明日方舟'],
  },
  {
    id: 'hidulume',
    name: 'Hidulume',
    cnName: 'ひづるめ',
    waiTag: 'hidulume',
    animaTag: '@hidulume',
    description: '强透视视线引导、丰富环境纵深与通透空气感光影',
    masterpiece: '《勇者斗恶龙 III HD-2D》概念艺术、《崩坏：星穹铁道》、《原神》',
    category: 'cinematic',
    verification: 'curated',
    keywords: ['hidulume', 'ひづるめ', 'hidzz', '视线诱导', '透视', '勇者斗恶龙', '星穹铁道', '流萤', '黑塔', '通透', '光影', '纵深', '电影感'],
  },

  // ── 清透少女与顶级 Galgame / 动漫画风 ───────────────────────────
  {
    id: 'kantoku',
    name: 'Kantoku',
    cnName: '监督',
    waiTag: 'kantoku',
    animaTag: '@kantoku',
    description: '清透日系美少女、柔和暖阳与干净线条',
    masterpiece: '《变态王子与不笑猫》、《如果有妹妹就好了》原案',
    category: 'pure',
    verification: 'curated',
    keywords: ['格子裙', '变态王子', '阳光', '清纯', 'galgame'],
  },
  {
    id: 'momoco_haru',
    name: 'Momoco',
    cnName: 'ももこ',
    waiTag: 'momoco_haru',
    animaTag: '@momoco haru',
    description: '《俄妹》轻小说原案、水润眼眸与元气白皙少女感',
    masterpiece: '《不时轻声用俄语遮羞的邻座艾莉同学》（俄妹）小说原案插画',
    category: 'pure',
    verification: 'curated',
    keywords: ['俄妹', '艾莉', '不时以俄语遮羞', '邻座艾莉', '轻小说', '水润', '通透', 'ももこ', 'momoco'],
  },
  {
    id: 'ponkan8',
    name: 'Ponkan8',
    cnName: 'ぽんかん⑧',
    waiTag: 'ponkan8',
    animaTag: '@ponkan8',
    description: '《春物》原案、清透水彩赛璐珞与青春明媚感',
    masterpiece: '《我的青春恋爱物语果然有问题。》（大春物）小说原案插画',
    category: 'pure',
    verification: 'curated',
    keywords: ['春物', '大春物', '由比滨', '雪乃', '青春', '水彩'],
  },
  {
    id: 'shirotaka',
    name: 'Shirotaka',
    cnName: 'シロタカ',
    waiTag: 'shirotaka',
    animaTag: '@shirotaka',
    description: '《无职转生》原案插画、细腻奇幻冒险与柔和水润光泽',
    masterpiece: '《无职转生 ～到了异世界就拿出真本事～》小说原案插画',
    category: 'pure',
    verification: 'curated',
    keywords: ['无职转生', '希露菲', '洛琪希', '艾莉丝', '奇幻', '水润'],
  },
  {
    id: 'abe_tsukasa',
    name: 'Abe Tsukasa',
    cnName: '阿部司',
    waiTag: 'abe_tsukasa',
    animaTag: '@abe tsukasa',
    description: '《葬送的芙莉莲》作画、古典厚重大气与静谧电影感',
    masterpiece: '《葬送的芙莉莲》（Frieren）漫画原作作画',
    category: 'pure',
    verification: 'curated',
    keywords: ['芙莉莲', '菲伦', '休塔尔克', '静谧', '古典', '电影感'],
  },
  {
    id: 'fujiwara_cocoa',
    name: 'Fujiwara Cocoa',
    cnName: '藤原可可亚',
    waiTag: 'fujiwara_cocoa',
    animaTag: '@fujiwara cocoa',
    description: '《妖狐×仆SS》原作者、极具灵气的哥特清冷与软萌气质',
    masterpiece: '《妖狐×仆SS》、《曾经有些魔法少女与邪恶为敌》',
    category: 'pure',
    verification: 'curated',
    keywords: ['妖仆', '魔法少女与邪恶', '白夜', '清冷', '萌系'],
  },
  {
    id: 'kazutake_hazano',
    name: 'Kazutake Hazano',
    cnName: '和武叶佐乃',
    waiTag: 'kazutake_hazano',
    animaTag: '@kazutake hazano',
    description: '《白圣女与黑牧师》原作者、温暖治愈系与圣洁柔和线条',
    masterpiece: '《白圣女与黑牧师》漫画原作',
    category: 'pure',
    verification: 'curated',
    keywords: ['白圣女', '塞西莉亚', '治愈', '圣洁', '柔和'],
  },
  {
    id: 'azuuru',
    name: 'Azure',
    cnName: 'あずーる',
    waiTag: 'azuuru',
    animaTag: '@azuuru',
    description: '《魔女之旅》原案、空灵水彩发丝与通透旅行感',
    masterpiece: '《魔女之旅》（伊蕾娜）、《天才王子的赤字国家重生术》',
    category: 'pure',
    verification: 'tag',
    keywords: ['魔女之旅', '伊蕾娜', '伊雷娜', 'elaina', 'azure', 'azuuru', '旅行', '魔女', '水彩', '通透'],
  },
  {
    id: 'hiten_(hitenkei)',
    name: 'Hiten',
    cnName: 'Hiten',
    waiTag: 'hiten_(hitenkei)',
    animaTag: '@hiten \\(hitenkei\\)',
    description: '柔光日系、精致五官与清澈治愈空气感',
    masterpiece: '《义妹生活》、《三角距离恋爱挺难》轻小说插画',
    category: 'pure',
    verification: 'tag',
    keywords: ['空气感', '柔光', '精致', '唯美', '清纯', '义妹生活'],
  },
  {
    id: 'tiv',
    name: 'Tiv',
    cnName: 'Tiv',
    waiTag: 'tiv',
    animaTag: '@tiv',
    description: '轻小说封面感、细腻环境光与微风发丝',
    masterpiece: '《政宗君的复仇》漫画作画、《偶像大师 百万现场》插画',
    category: 'pure',
    verification: 'tag',
    keywords: ['政宗君', '微风', '轻小说', '回眸'],
  },
  {
    id: 'anmi',
    name: 'Anmi',
    cnName: 'Anmi',
    waiTag: 'anmi',
    animaTag: '@anmi',
    description: '轻盈马卡龙粉彩、水润水彩质感与优雅体态',
    masterpiece: '《少女前线》（索米/RFB/翠蜜）、《放学后的昴星团》',
    category: 'pure',
    verification: 'curated',
    keywords: ['粉彩', '水彩', '优雅', '泳装', '透明感', '少前'],
  },
  {
    id: 'tsunako',
    name: 'Tsunako',
    cnName: 'Tsunako',
    waiTag: 'tsunako',
    animaTag: '@tsunako',
    description: '《约会大作战》原案、可爱活力少女与明亮配色',
    masterpiece: '《约会大作战》（DATE A LIVE）、《超次元游戏 海王星》、《契约之吻》原案',
    category: 'pure',
    verification: 'tag',
    keywords: ['约会大作战', '狂三', '木更', '可爱', '少女', '海王星'],
  },
  {
    id: 'morikura_en',
    name: 'Morikura En',
    cnName: '森仓圆',
    waiTag: 'morikura_en',
    animaTag: '@morikura en',
    description: '明亮商业角色插画、日常自然光与元气感',
    masterpiece: '绊爱（Kizuna AI）官方角色设计、《丸井集团》商业动画',
    category: 'pure',
    verification: 'curated',
    keywords: ['绊爱', '日常', '元气', '商业插画'],
  },
  {
    id: 'paryi',
    name: 'Paryi',
    cnName: '帕里',
    waiTag: 'paryi',
    animaTag: '@paryi',
    description: '超人气美少女插画、柔顺发丝与明亮水灵少女感',
    masterpiece: 'Paryi 企划 VTuber（神乐Mea等）角色设计与个人画集',
    category: 'pure',
    verification: 'curated',
    keywords: ['发之神技', '美少女', '发丝', '水灵', '清透'],
  },
  {
    id: 'muririn',
    name: 'Muririn',
    cnName: '梦璃凛',
    waiTag: 'muririn',
    animaTag: '@muririn',
    description: '柚子社柔亮赛璐璐、圆润脸型与水灵透明感',
    masterpiece: '柚子社《魔女的夜宴》《千恋＊万花》《星光咖啡馆与死神之蝶》',
    category: 'pure',
    verification: 'project',
    keywords: ['柚子社', '宁宁', '夏目', '赛璐珞', '千恋万花'],
  },
  {
    id: 'kobuichi',
    name: 'Kobuichi',
    cnName: '小舞一',
    waiTag: 'kobuichi',
    animaTag: '@kobuichi',
    description: '柚子社利落原画、清晰轮廓与鲜亮配色',
    masterpiece: '柚子社《RIDDLE JOKER》《魔女的夜宴》《天使☆嚣嚣》',
    category: 'pure',
    verification: 'project',
    keywords: ['柚子社', '原画', '鲜亮', '轮廓'],
  },
  {
    id: 'nekotomi_chao',
    name: 'Nekotomi Chao',
    cnName: '猫富ちゃお',
    waiTag: 'nekotomi_chao',
    animaTag: '@nekotomi chao',
    description: '《俄妹》动画工房核心原画分镜、极灵动细线条与通透赛璐珞',
    masterpiece: '《不时轻声用俄语遮羞的邻座艾莉同学》动画工房核心原画',
    category: 'pure',
    verification: 'curated',
    keywords: ['俄妹', '艾莉', '不时以俄语遮羞', '动画工房', '灵动', '赛璐珞', '分镜', '原画', '萌系', 'doga kobo'],
  },
  {
    id: 'atdan',
    name: 'Atdan',
    cnName: 'Atdan',
    waiTag: 'atdan',
    animaTag: '@atdan',
    description: '成人向清纯少女系、细腻肤色与娇羞神情',
    masterpiece: '《碧蓝航线》（大凤/爱尔敏）同人画集、各类魅惑插画',
    category: 'pure',
    verification: 'curated',
    keywords: ['成人向', '清纯', '娇羞', '少女', '碧蓝航线'],
  },
  {
    id: 'jazz_jack',
    name: 'Jazz Jack',
    cnName: 'Jazz Jack',
    waiTag: 'jazz_jack',
    animaTag: '@jazz jack',
    description: '清爽少女系、利落线条与元气活力感',
    masterpiece: '《碧蓝航线》《蔚蓝档案》Q版与高人气元气同人',
    category: 'pure',
    verification: 'curated',
    keywords: ['清爽', '元气', '少女', '舰娘', '蔚蓝档案'],
  },
  {
    id: 'hisasi',
    name: 'Hisasi',
    cnName: 'Hisasi',
    waiTag: 'hisasi',
    animaTag: '@hisasi',
    description: '老牌成人向、柔润上色与甜腻娇羞氛围',
    masterpiece: '《魔装学园H×H》轻小说角色原案与插画',
    category: 'pure',
    verification: 'curated',
    keywords: ['成人向', '柔润', '娇羞', '甜腻'],
  },
  {
    id: 'suimya',
    name: 'Suimya',
    cnName: 'Suimya',
    waiTag: 'suimya',
    animaTag: '@suimya',
    description: '软色情氛围系、湿润光泽与慵懒私密感',
    masterpiece: '《东方Project》《碧蓝航线》同人水彩与私密氛围画集',
    category: 'pure',
    verification: 'curated',
    keywords: ['氛围', '湿润', '私密', '慵懒'],
  },
  {
    id: 'rucarachi',
    name: 'Rucarachi',
    cnName: 'Rucarachi',
    waiTag: 'rucarachi',
    animaTag: '@rucarachi',
    description: 'NIKKE 周年主视觉画师、细腻线条与柔和色彩的游戏角色同人绘',
    masterpiece: '《NIKKE》2.5 周年纪念主视觉、原神雷电将军与八重神子、绝区零同人',
    category: 'pure',
    verification: 'tag',
    keywords: ['nikke', '妮姬', '原神', '雷电将军', '八重神子', '阿蕾奇诺', '绝区零', '细腻', '同人', 'game fan art'],
  },

  // ── 潮流先锋与高饱和 ──────────────────────────────────────────
  {
    id: 'lam_(ramdayo)',
    name: 'LAM',
    cnName: 'LAM',
    waiTag: 'lam_(ramdayo)',
    animaTag: '@lam \\(ramdayo\\)',
    description: '极高饱和霓虹、硬朗潮流眼妆与前卫图形',
    masterpiece: '《宿命回响：命运节拍》、《东京离线少女》角色设计',
    category: 'trend',
    verification: 'tag',
    keywords: ['赛博', '霓虹', '眼妆', '潮流', '撞色', '宿命回响'],
  },
  {
    id: 'mika_pikazo',
    name: 'Mika Pikazo',
    cnName: 'Mika Pikazo',
    waiTag: 'mika_pikazo',
    animaTag: '@mika pikazo',
    description: '高饱和流行波普色、大胆几何撞色与活力',
    masterpiece: '任天堂《火焰之纹章 Engage》角色设计、辉夜月、Hakos Baelz',
    category: 'trend',
    verification: 'curated',
    keywords: ['辉夜月', '撞色', '活力', '波普', '火焰纹章'],
  },
  {
    id: 'bunbun',
    name: 'BUNBUN / abec',
    cnName: 'abec',
    waiTag: 'bunbun',
    animaTag: '@bunbun',
    description: '动态游戏主视觉、清晰服装设计与动作张力',
    masterpiece: '《刀剑神域》（SAO）、《结城友奈是勇者》角色原案',
    category: 'trend',
    verification: 'curated',
    keywords: ['刀剑神域', '动态', '动作', '帅气', 'SAO', '桐人', '亚丝娜'],
  },
  {
    id: 'fujimoto_tatsuki',
    name: 'Fujimoto Tatsuki',
    cnName: '藤本树',
    waiTag: 'fujimoto_tatsuki',
    animaTag: '@fujimoto tatsuki',
    description: '《电锯人》原作者、独特粗粝分镜、强烈的电影式张力与反叛感',
    masterpiece: '《电锯人》（Chainsaw Man）、《炎拳》、《蓦然回首 (Look Back)》',
    category: 'trend',
    verification: 'curated',
    keywords: ['电锯人', '蕾塞', '玛奇玛', '粗粝', '电影感', '张力', '炎拳'],
  },

  // ── 华丽厚涂与大片级主视觉 ────────────────────────────────────
  {
    id: 'takeuchi_takashi',
    name: 'Takeuchi Takashi',
    cnName: '武内崇',
    waiTag: 'takeuchi_takashi',
    animaTag: '@takeuchi takashi',
    description: 'TYPE-MOON 主画师、经典月姬/Fate 凛然眼眸与标志性英灵立绘',
    masterpiece: '《Fate/stay night》、《月姬》、《空之境界》、《Fate/Grand Order》',
    category: 'grand',
    verification: 'curated',
    keywords: ['fate', 'fgo', '贞德', '间桐樱', 'saber', 'typemoon', '月姬'],
  },
  {
    id: 'shirabi',
    name: 'Shirabi',
    cnName: '白身成',
    waiTag: 'shirabi',
    animaTag: '@shirabi',
    description: '利落厚重线条、鲜明轮廓与戏剧性主视觉',
    masterpiece: '《86 -不存在的战区-》、《龙王的工作！》、《无彩限的怪灵世界》',
    category: 'grand',
    verification: 'curated',
    keywords: ['86', '龙王的工作', '大片', '戏剧光'],
  },
  {
    id: 'ask_(askzy)',
    name: 'ASK',
    cnName: 'ASK',
    waiTag: 'ask_(askzy)',
    animaTag: '@ask \\(askzy\\)',
    description: '清冷贵气、丝滑平滑上色与克制高级感',
    masterpiece: '《明日方舟》（斯卡蒂/琴柳/黑键）、《Fate/Grand Order》',
    category: 'grand',
    verification: 'tag',
    keywords: ['清冷', '贵气', '高级感', '礼服', '丝滑', '明日方舟', '斯卡蒂'],
  },
  {
    id: 'hxxg',
    name: 'HxxG',
    cnName: '刃天',
    waiTag: 'hxxg',
    animaTag: '@hxxg',
    description: '大动态广角透视、炫彩特效逆光与空间深邃感',
    masterpiece: '《黑岩射手 FRAGMENT》角色原案、《FGO》礼装插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['黑岩射手', '透视', '广角', '特效', 'fgo'],
  },
  {
    id: 'nardack',
    name: 'Nardack',
    cnName: 'Nardack',
    waiTag: 'nardack',
    animaTag: '@nardack',
    description: '宝石色奇幻、华丽服装与璀璨发光细节',
    masterpiece: '《修罗场恋人！》、《世界末日的世界录》轻小说原案插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['宝石', '华丽', '奇幻', '发光'],
  },
  {
    id: 'fuzichoco',
    name: 'Fuzichoco',
    cnName: '藤原',
    waiTag: 'fuzichoco',
    animaTag: '@fuzichoco',
    description: '和风幻想世界、繁复多层水彩与装饰细节',
    masterpiece: '《八男？别闹了！》小说原案插画、《东方Project》官方同人画集',
    category: 'grand',
    verification: 'curated',
    keywords: ['和风', '繁复', '金箔', '水彩', '东方'],
  },
  {
    id: 'lack',
    name: 'lack',
    cnName: 'lack',
    waiTag: 'lack',
    animaTag: '@lack',
    description: '浓郁幻想厚涂、成熟厚重色彩与史诗氛围',
    masterpiece: '《Fate/Grand Order》（冈田以藏/狂气阿龙）、《Hololive》（不知火芙蕾雅）',
    category: 'grand',
    verification: 'tag',
    keywords: ['fgo', '厚涂', '成熟', '暗黑'],
  },
  {
    id: 'so-bin',
    name: 'so-bin',
    cnName: 'so-bin',
    waiTag: 'so-bin',
    animaTag: '@so-bin',
    description: '暗黑哥特油画厚涂、厚重织物与沉稳史诗感',
    masterpiece: '《OVERLORD》（不死者之王）小说原作插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['overlord', '哥特', '油画', '厚重', '不死者之王'],
  },
  {
    id: 'kousaki_rui',
    name: 'Kousaki',
    cnName: '光崎',
    waiTag: 'kousaki_rui',
    animaTag: '@kousaki rui',
    description: 'FGO 主视觉感、精致优雅上色与端庄华美氛围',
    masterpiece: '《Fate/Grand Order》高人气同人画集《CHALDEA GLAMOUR》',
    category: 'grand',
    verification: 'tag',
    keywords: ['fgo', '优雅', '精致', '端庄', '华丽', '黑贞德'],
  },
  {
    id: 'xinzoruo',
    name: 'Xinzoruo',
    cnName: 'Xinzoruo',
    waiTag: 'xinzoruo',
    animaTag: '@xinzoruo',
    description: '成人向魅惑暗系、深邃光影与危险氛围',
    masterpiece: '《原神》高人气同人漫画与插画（艾尔海森/卡维/神里绫人）',
    category: 'grand',
    verification: 'curated',
    keywords: ['成人向', '魅惑', '暗色', '光影', '原神'],
  },
  {
    id: 'gweda',
    name: 'Gweda',
    cnName: 'Gweda',
    waiTag: 'gweda',
    animaTag: '@gweda',
    description: '精致韩系厚涂美少女、柔光玻璃质感与亮丽色彩',
    masterpiece: '《明日方舟》《NIKKE》《崩坏：星穹铁道》等游戏高人气同人（Danbooru artist id 176025，2000+ 作品）',
    category: 'grand',
    verification: 'tag',
    keywords: ['韩系', '厚涂', '精致', '柔光', '玻璃质感', '明日方舟', 'nikke', '崩铁'],
  },
  {
    id: 'eufoniuz',
    name: 'Eufoniuz',
    cnName: 'Eufoniuz',
    waiTag: 'eufoniuz',
    animaTag: '@eufoniuz',
    description: '成人向软萌少女同人、平滑肤色与娇甜私密氛围',
    masterpiece: '《电锯人》《我推的孩子》等成人向同人插画（Danbooru 专属 tag，Patreon/Fantia 连载）',
    category: 'pure',
    verification: 'tag',
    keywords: ['成人向', '软萌', '少女', '娇甜', '电锯人', '我推的孩子', '色气'],
  },
  {
    id: 'solar_(happymonk)',
    name: 'Solar (Happymonk)',
    cnName: 'SOLar_Bim',
    waiTag: 'solar_(happymonk)',
    animaTag: '@solar \\(happymonk\\)',
    description: '游戏角色色气同人、明亮肌肤与魅惑神情',
    masterpiece: '《Fate/Grand Order》（玛修/杨贵妃）、《蔚蓝档案》（明日奈/花凛）高人气同人（Danbooru tag 394+ 作品，Twitter @SOLar_Bim）',
    category: 'pure',
    verification: 'tag',
    keywords: ['成人向', '色气', 'fgo', '玛修', '蔚蓝档案', '明日奈', '游戏同人', 'SOLar_Bim'],
  },
  {
    id: 'alllisso',
    name: 'Alllisso',
    cnName: 'alllisso',
    waiTag: 'alllisso',
    animaTag: '@alllisso',
    description: 'Danbooru 专属画师 tag（189 作品），游戏角色同人',
    category: 'pure',
    verification: 'tag',
    keywords: ['同人', 'pixiv', 'twitter'],
  },
  {
    id: 'mesilmen',
    name: 'Mesilmen',
    cnName: 'mesilmen',
    waiTag: 'mesilmen',
    animaTag: '@mesilmen',
    description: 'Danbooru 专属画师 tag（73 作品），成人向游戏角色同人',
    category: 'pure',
    verification: 'tag',
    keywords: ['同人', 'pixiv', 'twitter'],
  },
  // ── 官方原画师区段已抽至 ./artistStyleCatalogOfficial.ts（2026-09-05 单体拆分）
  ...ARTIST_STYLE_OFFICIAL_OPTIONS,
])
