import type { ArtistStyleOption } from './artistStyles.ts'

export const FEATURE_STYLE_OPTIONS: readonly ArtistStyleOption[] = Object.freeze([
  // ── 潮流先锋与高饱和 ──────────────────────────────────────────
  {
    id: 'lam_(ramdayo)',
    name: 'LAM',
    cnName: 'LAM',
    waiTag: 'lam_(ramdayo)',
    animaTag: '@lam \\(ramdayo\\)',
    description: '极高饱和霓虹、硬朗潮流眼妆与前卫图形',
    masterpiece: '《宿命回响：命运节拍》、《东京离线少女》角色设计',
    category: 'trend',
    verification: 'tag',
    keywords: ['赛博', '霓虹', '眼妆', '潮流', '撞色', '宿命回响'],
  },
  {
    id: 'mika_pikazo',
    name: 'Mika Pikazo',
    cnName: 'Mika Pikazo',
    waiTag: 'mika_pikazo',
    animaTag: '@mika pikazo',
    description: '高饱和流行波普色、大胆几何撞色与活力',
    masterpiece: '任天堂《火焰之纹章 Engage》角色设计、辉夜月、Hakos Baelz',
    category: 'trend',
    verification: 'curated',
    keywords: ['辉夜月', '撞色', '活力', '波普', '火焰纹章'],
  },
  {
    id: 'bunbun',
    name: 'BUNBUN / abec',
    cnName: 'abec',
    waiTag: 'bunbun',
    animaTag: '@bunbun',
    description: '动态游戏主视觉、清晰服装设计与动作张力',
    masterpiece: '《刀剑神域》（SAO）、《结城友奈是勇者》角色原案',
    category: 'trend',
    verification: 'curated',
    keywords: ['刀剑神域', '动态', '动作', '帅气', 'SAO', '桐人', '亚丝娜'],
  },
  {
    id: 'fujimoto_tatsuki',
    name: 'Fujimoto Tatsuki',
    cnName: '藤本树',
    waiTag: 'fujimoto_tatsuki',
    animaTag: '@fujimoto tatsuki',
    description: '《电锯人》原作者、独特粗粝分镜、强烈的电影式张力与反叛感',
    masterpiece: '《电锯人》（Chainsaw Man）、《炎拳》、《蓦然回首 (Look Back)》',
    category: 'trend',
    verification: 'curated',
    keywords: ['电锯人', '蕾塞', '玛奇玛', '粗粝', '电影感', '张力', '炎拳'],
  },

  // ── 华丽厚涂与大片级主视觉 ────────────────────────────────────
  {
    id: 'takeuchi_takashi',
    name: 'Takeuchi Takashi',
    cnName: '武内崇',
    waiTag: 'takeuchi_takashi',
    animaTag: '@takeuchi takashi',
    description: 'TYPE-MOON 主画师、经典月姬/Fate 凛然眼眸与标志性英灵立绘',
    masterpiece: '《Fate/stay night》、《月姬》、《空之境界》、《Fate/Grand Order》',
    category: 'grand',
    verification: 'curated',
    keywords: ['fate', 'fgo', '贞德', '间桐樱', 'saber', 'typemoon', '月姬'],
  },
  {
    id: 'shirabi',
    name: 'Shirabi',
    cnName: '白身成',
    waiTag: 'shirabi',
    animaTag: '@shirabi',
    description: '利落厚重线条、鲜明轮廓与戏剧性主视觉',
    masterpiece: '《86 -不存在的战区-》、《龙王的工作！》、《无彩限的怪灵世界》',
    category: 'grand',
    verification: 'curated',
    keywords: ['86', '龙王的工作', '大片', '戏剧光'],
  },
  {
    id: 'ask_(askzy)',
    name: 'ASK',
    cnName: 'ASK',
    waiTag: 'ask_(askzy)',
    animaTag: '@ask \\(askzy\\)',
    description: '清冷贵气、丝滑平滑上色与克制高级感',
    masterpiece: '《明日方舟》（斯卡蒂/琴柳/黑键）、《Fate/Grand Order》',
    category: 'grand',
    verification: 'tag',
    keywords: ['清冷', '贵气', '高级感', '礼服', '丝滑', '明日方舟', '斯卡蒂'],
  },
  {
    id: 'hxxg',
    name: 'HxxG',
    cnName: '刃天',
    waiTag: 'hxxg',
    animaTag: '@hxxg',
    description: '大动态广角透视、炫彩特效逆光与空间深邃感',
    masterpiece: '《黑岩射手 FRAGMENT》角色原案、《FGO》礼装插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['黑岩射手', '透视', '广角', '特效', 'fgo'],
  },
  {
    id: 'nardack',
    name: 'Nardack',
    cnName: 'Nardack',
    waiTag: 'nardack',
    animaTag: '@nardack',
    description: '宝石色奇幻、华丽服装与璀璨发光细节',
    masterpiece: '《修罗场恋人！》、《世界末日的世界录》轻小说原案插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['宝石', '华丽', '奇幻', '发光'],
  },
  {
    id: 'fuzichoco',
    name: 'Fuzichoco',
    cnName: '藤原',
    waiTag: 'fuzichoco',
    animaTag: '@fuzichoco',
    description: '和风幻想世界、繁复多层水彩与装饰细节',
    masterpiece: '《八男？别闹了！》小说原案插画、《东方Project》官方同人画集',
    category: 'grand',
    verification: 'curated',
    keywords: ['和风', '繁复', '金箔', '水彩', '东方'],
  },
  {
    id: 'lack',
    name: 'lack',
    cnName: 'lack',
    waiTag: 'lack',
    animaTag: '@lack',
    description: '浓郁幻想厚涂、成熟厚重色彩与史诗氛围',
    masterpiece: '《Fate/Grand Order》（冈田以藏/狂气阿龙）、《Hololive》（不知火芙蕾雅）',
    category: 'grand',
    verification: 'tag',
    keywords: ['fgo', '厚涂', '成熟', '暗黑'],
  },
  {
    id: 'so-bin',
    name: 'so-bin',
    cnName: 'so-bin',
    waiTag: 'so-bin',
    animaTag: '@so-bin',
    description: '暗黑哥特油画厚涂、厚重织物与沉稳史诗感',
    masterpiece: '《OVERLORD》（不死者之王）小说原作插画',
    category: 'grand',
    verification: 'curated',
    keywords: ['overlord', '哥特', '油画', '厚重', '不死者之王'],
  },
  {
    id: 'kousaki_rui',
    name: 'Kousaki',
    cnName: '光崎',
    waiTag: 'kousaki_rui',
    animaTag: '@kousaki rui',
    description: 'FGO 主视觉感、精致优雅上色与端庄华美氛围',
    masterpiece: '《Fate/Grand Order》高人气同人画集《CHALDEA GLAMOUR》',
    category: 'grand',
    verification: 'tag',
    keywords: ['fgo', '优雅', '精致', '端庄', '华丽', '黑贞德'],
  },
  {
    id: 'xinzoruo',
    name: 'Xinzoruo',
    cnName: 'Xinzoruo',
    waiTag: 'xinzoruo',
    animaTag: '@xinzoruo',
    description: '成人向魅惑暗系、深邃光影与危险氛围',
    masterpiece: '《原神》高人气同人漫画与插画（艾尔海森/卡维/神里绫人）',
    category: 'grand',
    verification: 'curated',
    keywords: ['成人向', '魅惑', '暗色', '光影', '原神'],
  },
  {
    id: 'gweda',
    name: 'Gweda',
    cnName: 'Gweda',
    waiTag: 'gweda',
    animaTag: '@gweda',
    description: '精致韩系厚涂美少女、柔光玻璃质感与亮丽色彩',
    masterpiece: '《明日方舟》《NIKKE》《崩坏：星穹铁道》等游戏高人气同人（Danbooru artist id 176025，2000+ 作品）',
    category: 'grand',
    verification: 'tag',
    keywords: ['韩系', '厚涂', '精致', '柔光', '玻璃质感', '明日方舟', 'nikke', '崩铁'],
  },
  {
    id: 'eufoniuz',
    name: 'Eufoniuz',
    cnName: 'Eufoniuz',
    waiTag: 'eufoniuz',
    animaTag: '@eufoniuz',
    description: '成人向软萌少女同人、平滑肤色与娇甜私密氛围',
    masterpiece: '《电锯人》《我推的孩子》等成人向同人插画（Danbooru 专属 tag，Patreon/Fantia 连载）',
    category: 'pure',
    verification: 'tag',
    keywords: ['成人向', '软萌', '少女', '娇甜', '电锯人', '我推的孩子', '色气'],
  },
  {
    id: 'solar_(happymonk)',
    name: 'Solar (Happymonk)',
    cnName: 'SOLar_Bim',
    waiTag: 'solar_(happymonk)',
    animaTag: '@solar \\(happymonk\\)',
    description: '游戏角色色气同人、明亮肌肤与魅惑神情',
    masterpiece: '《Fate/Grand Order》（玛修/杨贵妃）、《蔚蓝档案》（明日奈/花凛）高人气同人（Danbooru tag 394+ 作品，Twitter @SOLar_Bim）',
    category: 'pure',
    verification: 'tag',
    keywords: ['成人向', '色气', 'fgo', '玛修', '蔚蓝档案', '明日奈', '游戏同人', 'SOLar_Bim'],
  },
  {
    id: 'alllisso',
    name: 'Alllisso',
    cnName: 'alllisso',
    waiTag: 'alllisso',
    animaTag: '@alllisso',
    description: 'Danbooru 专属画师 tag（189 作品），游戏角色同人',
    category: 'pure',
    verification: 'tag',
    keywords: ['同人', 'pixiv', 'twitter'],
  },
  {
    id: 'mesilmen',
    name: 'Mesilmen',
    cnName: 'mesilmen',
    waiTag: 'mesilmen',
    animaTag: '@mesilmen',
    description: 'Danbooru 专属画师 tag（73 作品），成人向游戏角色同人',
    category: 'pure',
    verification: 'tag',
    keywords: ['同人', 'pixiv', 'twitter'],
  },
])
