const EXACT_MEANINGS: Record<string, string> = {
  nene_r18: '宁宁成人状态门控词',
  natsume_r18: '夏目成人状态门控词',
  nene_witch_canonical: '宁宁经典魔女服主控制词',
  nene_school_uniform: '宁宁学院制服主控制词',
  nene_sailor_uniform: '宁宁水手制服主控制词',
  nene_blue_pajamas: '宁宁蓝色睡衣主控制词',
  nene_green_sleepwear: '宁宁绿色睡衣主控制词',
  nene_red_cardigan_uniform: '宁宁红色开衫制服主控制词',
  natsume_official_qipao: '夏目官方旗袍主控制词',
  natsume_cafe_uniform: '夏目咖啡馆制服主控制词',
  natsume_maid_uniform: '夏目女仆服主控制词',
  natsume_sleepwear: '夏目睡衣主控制词',
  virgin_killer_sweater: '露背高领毛衣 (童贞杀手)',
  backless_sweater: '大露背针织衫',
  turtleneck_sweater: '高领毛衣',
  ribbed_sweater: '修身罗纹毛衣',
  oversized_sweater: '宽松大号毛衣',
  off_shoulder_sweater: '露肩针织衫',
  keyhole_sweater: '胸口开孔毛衣',
  bunny_suit: '兔女郎连体衣',
  sheer_bunny_suit: '半透明情趣兔女郎',
  reverse_bunny_suit: '逆兔女郎 (反向深V)',
  bodysuit: '贴身连体衣',
  sleeveless_bodysuit: '无袖紧身连体衣',
  backless_bodysuit: '大露背紧身连体衣',
  'skin-tight': '极致紧致包裹 / 贴肤',
  latex_catsuit: '紧身漆皮胶衣',
  triangle_bikini: '三角杯细带比基尼',
  'front-tie_bikini': '前系带蝴蝶结比基尼',
  bandeau_bikini: '无肩带抹胸比基尼',
  'criss-cross_bikini': '交叉缠腰绑带水着',
  micro_bikini: '微型系绳比基尼',
  minimal_fabric: '极少极窄布料',
  competitive_swimsuit: '竞速高开衩死库水',
  competition_swimsuit: '专业竞速死库水',
  white_competition_swimsuit: '纯白高开叉竞泳水着',
  highleg_swimsuit: '高开衩连体泳装',
  monokini: '挂脖镂空连体泳衣 (Monokini)',
  halterneck_swimsuit: '挂脖系带泳装',
  side_cutout: '腰侧大面积镂空',
  cleavage_cutout: '胸口开孔镂空',
  heart_cutout: '心形开胸镂空',
  cleavage_opening: '深邃开胸露乳线',
  sleeveless_turtleneck: '无袖修身高领',
  wet_white_shirt: '海滩湿透白衬衫',
  'see-through_shirt': '透光薄衬衫',
  bikini_under_clothes: '内穿比基尼 (若隐若现)',
  oversized_jersey: '宽大男友风运动球衣',
  basketball_jersey: '无袖篮球背心球衣',
  sleeveless_jersey: '无袖透气球衣',
  santa_costume: '红白雪绒圣诞装',
  santa_capelet: '圣诞连帽短斗篷',
  succubus_costume: '小恶魔/魅魔装',
  sheer_babydoll: '透明薄纱睡袍 (Babydoll)',
  'open-front_negligee': '前开襟透肉睡衣',
  silk_slip: '真丝细吊带衬裙',
  garter_straps: '吊带袜金属束带',
  black_pantyhose: '薄透透肉黑丝袜',
  fishnet_thighhighs: '过膝网眼袜',
  torn_thighhighs: '战损撕裂丝袜',
  loose_socks: '日系宽松堆堆袜',
  frilled_socks: '荷叶边花边短袜',
  asymmetrical_legwear: '不对称腿袜',
  stiletto_heels: '尖头细高跟鞋',
  strappy_heels: '绑带缠踝高跟凉鞋',
  mary_janes: '玛丽珍复古皮鞋',
  thigh_boots: '过膝紧身皮靴',
  combat_boots: '系带马丁靴',
  barefoot: '赤足 / 美足',
  painted_toenails: '涂指甲油脚趾',
  looking_at_viewer: '直视镜头',
  looking_back: '回头看向镜头',
  direct_eye_contact: '与镜头直接对视',
  full_body: '全身构图',
  upper_body: '上半身构图',
  medium_shot: '中景构图',
  close_up: '近景特写',
  wide_shot: '广角远景',
  face_focus: '面部重点清晰',
  soft_lighting: '柔和光线',
  warm_lighting: '暖色光线',
  morning_light: '晨间光线',
  window_light: '窗边自然光',
  cinematic_composition: '电影感构图',
  official_visual_novel_cg_framing: '官方视觉小说 CG 构图',
  natural_body_proportions: '自然身体比例',
  clearly_different_faces: '角色脸部特征清晰区分',
  two_red_hairclips: '两枚红色发夹',
  mole_under_eye: '眼下泪痣',
  no_hair_ribbon: '不使用发带',
  very_long_black_hair: '极长黑发',
  golden_yellow_eyes: '金黄色眼睛',
  white_silver_hair: '银白色头发',
  very_long_low_twintails: '极长低双马尾',
  black_thighhighs: '黑色过膝袜',
  black_thighhigh_stockings: '黑色大腿袜',
  cherry_blossoms: '樱花',
  school_rooftop: '学校天台',
  cafe: '咖啡馆',
  bookstore_interior: '书店室内',
  bedroom: '卧室',
  sunset: '黄昏日落',
  golden_hour: '日落黄金时刻',
  rainy_night: '雨夜',
  starry_sky: '星空',
  subtle_blush: '轻微脸红',
  reserved_smile: '克制的微笑',
  shy_direct_eye_contact: '害羞地直视镜头',
  holding_hands: '牵手',
  on_bed: '在床上',
  side_view: '侧面视角',
  pov: '第一人称视角',
  // 场景库高频复合词 + 角色名
  ayachi_nene: '绫地宁宁',
  shiki_natsume: '四季夏目',
  in_love: '恋爱中',
  expectant: '期待的神情',
  peeking_out: '探出头偷看',
  dust_motes: '漂浮的尘埃',
  over_shoulder: '回眸过肩',
  crowd: '人群',
  lanterns: '灯笼',
  snowfall: '下雪',
  romantic_atmosphere: '浪漫氛围',
  overcast: '阴天',
  torii: '鸟居',
  relaxed: '放松',
  sundress: '太阳裙',
  melancholic: '忧郁',
  chalkboard: '黑板',
  steam: '蒸汽',
  breath_vapor: '呼吸的白气',
  splashing_water: '水花四溅',
  railing: '栏杆',
  bookshelf: '书架',
  backlighting: '逆光',
  handmade_charm: '手工护身符',
  christmas_lights: '圣诞彩灯',
  winter_coat: '冬季外套',
  sharing_scarf: '共围一条围巾',
  gift: '礼物',
  scarf: '围巾',
  profile: '侧面剪影',
  reaching_out: '伸手',
  leaning_against: '倚靠着',
  sitting_on_lap: '坐在膝上',
  straddling: '跨坐',
  clinging: '依偎',
  resting_head: '头靠着',
  interlocked_fingers: '十指相扣',
  close_face_to_face: '面对面贴近',
  warm_soft_light: '温暖柔光',
  window_seat: '窗边座位',
  single_flower: '一枝花',
  holding_umbrella: '撑伞',
  holding_papers: '拿着文件',
  waiting_for: '等待',
  crowded: '拥挤的',
  festival_lanterns: '祭典灯笼',
  winter_breath: '冬日哈气',
  milk_carton: '牛奶盒',
  ice_cream: '冰淇淋',
  shaved_ice: '刨冰',
  popsicle: '冰棍',
  hot_dog: '热狗',
  takoyaki: '章鱼烧',
  crepe: '可丽饼',
  taiyaki: '鲷鱼烧',
  cotton_candy: '棉花糖',
  yakisoba: '炒面',
  shaved_ice_stand: '刨冰摊',
  festival_stall: '祭典摊位',
  ginkgo: '银杏',
  persimmon: '柿子',
  hot_spring: '温泉',
  footbath: '足汤',
  ryokan: '旅馆',
  tatami: '榻榻米',
  sliding_door: '推拉门',
  shoji: '纸拉门',
  kotatsu: '暖桌',
  futon: '被褥',
  haori: '羽织',
  obi: '腰带',
  geta: '木屐',
  sandals: '凉鞋',
  sneakers: '运动鞋',
  loafers: '皮鞋',
  boots: '靴子',
  mittens: '连指手套',
  gloves: '手套',
  earmuffs: '耳罩',
  beanie: '毛线帽',
  beret: '贝雷帽',
  cap: '帽子',
  hood: '兜帽',
  zipper: '拉链',
  buttons: '纽扣',
  collar: '衣领',
  sleeves: '袖子',
  hem: '下摆',
  waist: '腰部',
  neck: '颈部',
  wrist: '手腕',
  ankle: '脚踝',
  freckles: '雀斑',
  dimples: '酒窝',
  fang: '小虎牙',
  sharp_teeth: '尖牙',
  tongue_out: '吐舌',
  open_mouth: '张嘴',
  parted_lips: '微张的唇',
  half_closed_eyes: '半闭的眼',
  closed_eyes: '闭眼',
  sparkling_eyes: '闪闪发亮的眼睛',
  narrowed_eyes: '眯眼',
  wide_eyes: '睁大眼睛',
  unfocused: '失焦',
  heavy_blush: '满脸通红',
  red_ears: '红耳朵',
  sweatdrop: '汗滴',
  teary: '含泪',
  trembling: '颤抖',
  shocked: '震惊',
  dazed: '恍惚',
  daydreaming: '发呆',
  focused: '专注',
  determined: '坚定',
  confident: '自信',
  proud: '骄傲',
  smug: '得意',
  mischievous: '调皮',
  playful: '俏皮',
  teasing: '逗弄',
  scolding: '教训',
  sulking: '闹别扭',
  whining: '撒娇抱怨',
  pleading: '恳求',
  embarrassed: '难为情',
  flustered: '慌乱',
  panicked: '惊慌',
  cautious: '小心翼翼',
  curious: '好奇',
  hesitant: '犹豫',
  reluctant: '不情愿',
  resigned: '认命',
  relieved: '松一口气',
  grateful: '感激',
  touched: '感动',
  nostalgic: '怀念',
  wistful: '惆怅',
  lonely: '孤独',
  desolate: '落寞',
  peaceful: '安宁',
  serene: '恬静',
  cozy: '温馨',
  lively: '热闹',
  bustling: '熙攘',
  quiet: '安静',
  still: '静止',
  motionless: '静止',
  frozen: '凝固',
  blowing: '飘动',
  drifting: '飘落',
  floating: '漂浮',
  swaying: '摇曳',
  flickering: '闪烁',
  glowing: '发光',
  gleaming: '微光',
  shiny: '亮泽',
  glossy: '光泽',
  matte: '哑光',
  transparent: '透明',
  translucent: '半透明',
  opaque: '不透明',
  faded: '褪色',
  vivid: '鲜艳',
  muted: '柔和',
  pastel: '粉彩',
  saturated: '饱和',
  desaturated: '低饱和',
  monochrome: '单色',
  sepia: '棕褐',
  contrast: '对比',
  highlights: '高光',
  rim: '边缘',
  edge: '边缘',
  silhouette_light: '轮廓光',
  soft_focus: '柔焦',
  shallow_depth: '浅景深',
  bokeh: '散景光斑',
  lens_flare: '镜头光晕',
  grain: '颗粒',
  noise: '噪点',
  vignette: '暗角',
  fisheye: '鱼眼',
  panoramic: '全景',
  landscape: '横构图',
  portrait_orientation: '竖构图',
  symmetrical: '对称',
  asymmetric: '不对称',
  diagonal: '对角',
  layered: '层次',
  depth: '纵深',
  perspective: '透视',
  vanishing_point: '消失点',
  leading_lines: '引导线',
  negative_space: '留白',
  minimalist: '极简',
  maximalist: '繁复',
  detailed_background: '精细背景',
  simple_background: '简约背景',
  gradient_background: '渐变背景',
  solid_background: '纯色背景',
  patterned: '花纹',
  polka_dot: '波点',
  gingham: '格纹布',
  lace: '蕾丝',
  silk: '丝绸',
  satin: '缎面',
  velvet: '天鹅绒',
  denim: '牛仔布',
  leather: '皮革',
  wool: '羊毛',
  knit: '针织',
  cashmere: '羊绒',
  cotton: '棉',
  linen: '亚麻',
  chiffon: '雪纺',
  mesh: '网纱',
  sequins: '亮片',
  pearls: '珍珠',
  beads: '珠子',
  lace_trim: '蕾丝边',
  ruffle: '荷叶边',
  frill: '花边',
  tulle: '薄纱',
  organza: '欧根纱',
  exam_paper: '试卷', camping: '露营', campfire: '篝火', under_eaves: '屋檐下',
  adjusting_scarf: '整理围巾', theater_backstage: '剧场后台', stage_costume: '戏服',
  curtain: '窗帘', solid_color: '纯色', cohabitation: '同居', game_controller: '游戏手柄',
  pouting: '嘟嘴', new_year: '新年', sunbeam: '一束阳光', photo_album: '相册',
  shooting_star: '流星', starlight: '星光', aquarium: '水族馆', home_interior: '家居内饰',
  vending_machine: '自动贩卖机', drinking_fountain: '饮水机', water_heater: '热水器',
  microwave: '微波炉', refrigerator: '冰箱', coffee_maker: '咖啡机', espresso: '浓缩咖啡',
  matcha: '抹茶', tea_cup: '茶杯', sake: '清酒', ramen: '拉面', udon: '乌冬面',
  soba: '荞麦面', rice_bowl: '盖饭', bento: '便当', onigiri: '饭团', omurice: '蛋包饭',
  curry: '咖喱', hamburger: '汉堡', pancakes: '松饼', waffles: '华夫饼', donuts: '甜甜圈',
  cookies: '饼干', cake: '蛋糕', chocolate: '巧克力', candy: '糖果', snacks: '零食',
  fruit: '水果', apple: '苹果', orange: '橙子', strawberry: '草莓', watermelon: '西瓜',
  grapes: '葡萄', peach: '桃子', melon: '哈密瓜', banana: '香蕉', lemon: '柠檬',
  soda: '汽水', juice: '果汁', milk: '牛奶', cocoa: '可可', honey: '蜂蜜',
  birthday: '生日', christmas: '圣诞节', halloween: '万圣节', valentine: '情人节',
  wedding: '婚礼', anniversary: '纪念日', celebration: '庆祝', party: '派对',
  balloon: '气球', confetti: '彩带', cake_candle: '蛋糕蜡烛', gift_box: '礼物盒',
  kite: '风筝', shuttlecock: '羽毛球', badminton: '羽毛球', tennis: '网球',
  basketball: '篮球', soccer: '足球', baseball: '棒球', swimming: '游泳',
  diving: '跳水', surfing: '冲浪', sailing: '帆船', fishing: '钓鱼', hiking: '徒步',
  picnic: '野餐', barbecue: '烧烤', stargazing: '观星', birdwatching: '观鸟',
  photography: '摄影', sketching: '速写', painting: '绘画', reading: '阅读',
  writing: '写作', playing_guitar: '弹吉他', piano_keyboard: '弹钢琴',
  dance: '跳舞', singing: '唱歌', karaoke: '卡拉OK', video_game: '电子游戏',
  board_game: '桌游', chess: '国际象棋', shogi: '将棋', mahjong: '麻将',
  card_game: '纸牌', trivia: '问答', lottery: '抽奖', fortune_telling: '占卜',
  excited: '兴奋', joy: '喜悦', blushing: '脸红', sweat: '汗水', sportswear: '运动服',
  reflection: '倒影', laboratory: '实验室', aquarium_tunnel: '水族馆隧道',
  whale_shark: '鲸鲨', short_bridal_veil: '短款婚纱头纱', intimate_call: '亲密通话',
  heart_rate_monitor: '心率监测器', monitoring_equipment: '监测设备',
  sensor_headset: '感应耳机', reaching_finish_line: '冲刺终点线',
  shared_halo: '共享光环', overhead: '头顶上方', on_the_left: '在左侧',
  on_the_right: '在右侧', behind_her: '在她身后', in_front: '在前方',
  beside: '在身旁', across: '横跨', around: '环绕', between: '之间',
  beneath: '在下方', above: '在上方', nearby: '附近', distant: '远处',
  close_by: '近旁', slightly: '微微', gently: '轻轻', softly: '轻柔地',
  quietly: '静静地', slowly: '缓缓', carefully: '小心翼翼地',   eagerly: '急切地',
  nervously: '紧张地', happily: '开心地', sadly: '难过地', tenderly: '温柔地',
  warmly: '温暖地', brightly: '明亮地', faintly: '隐约地', clearly: '清晰地',
  // ── 成人词条（R18 场景 / 词条浏览器共用） ──
  naked: '裸体', nude: '裸体', nudity: '裸体', breast: '胸部', breasts: '胸部',
  nipple: '乳头', nipples: '乳头', areola: '乳晕', lingerie: '内衣',
  lace_lingerie: '蕾丝内衣', midriff: '露腰', bare_midriff: '露腰',
  bare_abdomen: '裸露小腹', neck_kiss: '颈吻', passionate_look: '深情注视',
  private_bedroom: '私人卧室', garter_belt: '吊袜带', garter: '吊带',
  bra_lift: '掀起胸衣', intimate: '亲密',
  exactly_two_breasts: '恰好双乳', beige_panties_visible: '可见米色内裤',
  panties: '内裤', underwear: '内衣', thong: '丁字裤', bra: '胸罩',
  stockings: '长袜', thighhighs: '过膝袜', thighhigh: '过膝袜',
  bared: '裸露的', revealing: '暴露的', skimpy: '清凉的', erotic: '情色',
  lewd: '色气', seductive: '诱惑的', flirty: '撩人的', sensual: '性感的',
  sex: '性爱', making_love: '做爱', foreplay: '前戏', orgasm: '高潮',
  squirt: '潮吹', squirting: '潮吹', masturbation: '自慰', masturbating: '自慰中',
  vaginal: '阴道', anal: '肛交', missionary: '传教士体位', cowgirl: '骑乘位',
  doggystyle: '后入式', fellatio: '口交', blowjob: '口交', cunnilingus: '舔阴',
  handjob: '手交', creampie: '内射', cum: '精液', hickeys: '吻痕',
  love_bites: '吻痕', kiss_marks: '吻痕', bondage: '束缚', handcuffs: '手铐',
  tied_up: '被捆绑', blindfold: '眼罩', spanking: '打屁股', vibrator: '震动棒',
  dildo: '假阳具', sex_toys: '情趣玩具', kissing: '接吻', embrace: '拥抱', embracing: '拥抱',
  caressing: '抚摸', fondling: '爱抚', petting: '爱抚', snuggling: '依偎',
  spooning: '相拥而眠', lap_sitting: '坐在膝上', straddling_viewer: '跨坐面对镜头',
  trapped: '被困住', clinging_to: '依偎着', hugging_from_behind: '从背后环抱',
  bare_back: '裸露后背', bare_hips: '裸露臀部', bare_shoulders: '裸露肩膀',
  bared_chest: '敞开胸膛', open_shirt: '敞开衬衫', unbuttoned: '解开纽扣',
  pants_bulge: '裆部隆起', erection: '勃起', semi_erection: '半勃起',
  pubic_hair: '阴毛', shaved: '剃毛', cameltoe: '骆驼趾',
  no_bra: '真空（无胸罩）', no_panties: '真空（无内裤）', bare_legs: '裸腿',
  cleavage: '乳沟', sideboob: '侧乳', wet_skin: '湿身',
  bare_shoulders_and_cleavage: '裸露肩颈与乳沟',
 
  // ── 场景/目录补齐（第 2 轮） ──
  witch: '魔女', cape: '披风', elf: '精灵', tear: '泪珠', squatting: '蹲着',
  shivering: '发抖', cold: '寒冷', halo: '光环', hakama: '袴', frills: '花边',
  bonnet: '软帽', choker: '项圈', jeans: '牛仔裤', glasses: '眼镜',
  blanket: '毯子', attic: '阁楼', witch_hat: '女巫帽', crop_top: '短上衣',
  dudou: '肚兜', undergarment: '内衣', overalls: '背带裤', sleeveless: '无袖',
  backless: '露背', workshop: '工作间', sunlight: '阳光', sofa: '沙发',
  drunk: '醉酒', roomwear: '居家服', blouse: '衬衫', denim_shorts: '牛仔短裤',
  daytime: '白天', passionate: '激情', kiss: '亲吻', robe: '长袍',
  dryer: '烘干机', mirror: '镜子', lake: '湖泊', veil: '头纱',
  elevator: '电梯', unzipped: '拉链拉开', tsundere: '傲娇', office: '办公室',
  clubroom: '社团活动室', darkroom: '暗房', study: '书房', smirk: '得意笑',
  corset: '束腰', fishnets: '渔网袜', backlit: '逆光', biting: '咬',
  gym: '健身房', bound: '被捆绑', bedsheet: '床单', shorts: '短裤',
  garage: '车库', topless: '上身裸露', wet: '湿',
  hotel: '酒店', stream: '溪流', izakaya: '居酒屋', tired: '疲惫',
  canvas: '画布', thinking: '思考', iced_tea: '冰茶', cicadas: '蝉',
  washitsu: '和室', lakeside: '湖畔', twirling: '旋转', bathrobe: '浴袍',
  bloomers: '灯笼裤', backseat: '后座', arms_up: '举臂', tank_top: '背心',
  camisole: '吊带背心', sun_flare: '太阳光晕', volumetric: '体积光',
  dramatic: '戏剧光', anime_illustration: '动漫插画', visual_novel_cg: '视觉小说CG',
  game_illustration: '游戏插画', solo: '单人', adult: '成年',
  clear_sky: '晴朗天空',
 
  indoors: '室内', happy: '开心',
  calm: '平静', serious: '严肃',
  nervous: '紧张', dawn: '黎明', bed: '床',
  ocean: '海洋', lying_on_bed: '躺在床上', sitting_on_desk: '坐在书桌上',
  cross_legged: '盘腿', holding: '拿着', towel: '毛巾',
  tactical_gear: '战术装备',
  undressing: '脱衣', translucent_clothing: '半透明衣物', torn_clothes: '撕破的衣物',
  office_lady: '职业女性', messy_hair: '凌乱头发', hair_bun: '发髻',
  hair_flower: '发间花饰', windblown_hair: '被风吹动的头发',
  silhouette: '剪影', strong_shadows: '强烈阴影', soft_shadows: '柔和阴影',
  diffused_light: '漫射光', first_light: '破晓之光',
  lantern_light: '灯笼光', screen_light: '屏幕光', blue_hour: '蓝色时刻',
  teary_eyes: '含泪的眼睛', soft_eyes: '温柔的眼神', shy_smile: '害羞的微笑',
  bright_eyes: '明亮的眼睛', looking_up: '仰望',
  looking_away: '移开视线', from_behind: '从背后', from_below: '从下方',
  side_glance: '侧目', point_of_view: '视角', heavy_breathing: '粗重的呼吸',
  intense_look: '炽热的注视', seductive_look: '诱惑的眼神',
  spring: '春天',
  shared_umbrella: '共伞', under_blanket: '盖着毯子',
  sleepy: '困倦', pencil_skirt: '铅笔裙', legs_apart: '双腿分开',
  beach_house: '海边小屋', holding_wine_glass: '端着酒杯', bar_interior: '酒吧内景',
  pout: '嘟嘴', gold_bow: '金色蝴蝶结', vulnerable_expression: '脆弱的神情',
  festival: '祭典', beach_coverup: '沙滩罩衫',
  holding_phone: '拿着手机', late_night: '深夜',
  cityscape: '城市景观', disheveled_clothes: '凌乱的衣物',
  string_bikini: '细带比基尼',
  bikini_malfunction: '泳装滑落', untied_swimsuit: '解开的泳装',
  bound_hands: '被绑的双手', night_sky: '夜空',
  lying_on_stomach: '趴着', extreme_intimacy: '极度亲密', sitting_on_engawa: '坐在檐廊',
  wrapped_in_sheet: '裹着床单', shirt_lift: '掀起衬衫', witch_costume: '魔女装',
  black_cape: '黑色披风', pink_lining: '粉色内衬', striped_legwear: '条纹袜',
  intoxicated: '微醺', towel_slip: '浴巾滑落', dress_unzipped: '连衣裙拉链拉开',
  high_slit: '高开衩', safehouse: '安全屋', washroom: '盥洗室', dusk: '暮色',
  twilight: '黄昏', gaze: '注视', glance: '一瞥', stare: '凝视',
  wearing: '穿着', removing: '脱去', adjusting: '整理', fixing: '整理',
  straightening: '整理', pulling: '拉扯', lifting: '掀起', pushing: '推开',
  holding_up: '举起', reaching: '伸手', reaching_for: '伸手够',
  stepping: '迈步', walking_away: '走开', approaching: '走近',
  leaning_over: '俯身', bending_over: '弯腰', crouching: '蹲伏',
  arm_around: '搂着肩膀',
  head_on_shoulder: '头靠肩膀', leaning_on_shoulder: '靠在肩上',
  resting_hand: '手搭着', touching: '触碰', tracing: '轻抚',
  brushing: '轻拂', combing: '梳理', braiding: '编辫子',
  playing_with_hair: '玩着头发', twirling_hair: '绕着头发',
  carrying: '抱着', carrying_bridal_style: '公主抱', piggyback: '背着',
  shoulder_ride: '骑在肩上',
  arms_crossed: '双臂交叉', arm_up: '举起手臂', home_theater: '家庭影院',
  water_droplets: '水珠', breakroom: '休息室', indoor: '室内',
  transparent_clothing: '透明衣物', see_through_clothing: '透视装',
  daylight: '日光', feather_accessories: '羽毛饰品', baseball_cap: '棒球帽',
  slight_frown: '微微皱眉', expressionless: '面无表情', cool_style: '冷酷风格',
  flowers: '花朵', rose: '玫瑰', sunbeams: '光束', windy: '有风',
  race_queen: '赛车女郎', zipper_leotard: '拉链连体衣', round_glasses: '圆框眼镜',
  sharing_blanket: '共盖一条毯子', falling_forward: '前倾', cozy_atmosphere: '温馨氛围',
  propped_up_on_elbow: '手肘撑起', cheerleader: '啦啦队', denim_overalls: '牛仔背带裤',
  off_shoulder_top: '露肩上衣', bare_streaks: '露腰', shopping_basket: '购物篮',
  collarbone: '锁骨', shoulder_blade: '肩胛骨', underwear_strap: '内衣肩带',
  car_interior: '车内', lounge: '休息室', off_shoulder: '露肩', stone_stairs: '石阶',
  stage: '舞台', caring: '关爱',
  paper_fan: '纸扇', spotlight: '聚光灯', stairwell: '楼梯间', wall_lean: '靠墙',
  first_kiss: '初吻', laundromat: '洗衣店', wet_floor: '湿滑地面', cable_car: '缆车',
  milky_way: '银河', picnic_box: '野餐盒', bunny_ears: '兔耳',
  bare_feet: '赤脚', whispering: '耳语', fireplace: '壁炉', nurse_cap: '护士帽',
  from_above: '俯视', front_view: '正面视角', bottomless: '下空', silk_robe: '丝绸睡袍',
  warehouse: '仓库', art_studio: '画室',
  tears_of_joy: '喜悦的泪水', close_distance: '近距离',
}

const WORD_MEANINGS: Record<string, string> = {
  all: '全部', angle: '角度', angel: '天使', apron: '围裙', at: '在', back: '背部',
  background: '背景', beach: '海边', black: '黑色', blue: '蓝色', body: '身体', both: '双手',
  bow: '蝴蝶结', bookstore: '书店', brown: '棕色', bun: '发髻', camera: '镜头', campus: '校园',
  casual: '日常', chair: '椅子', china: '旗袍', chinese: '中式', city: '城市',
  classroom: '教室', clear: '晴朗', clothes: '服装', close: '近景', closed: '闭合', composition: '构图',
  contact: '接触', cream: '奶油色', cute: '可爱', dark: '深色', day: '白天', desk: '书桌',
  detailed: '细节丰富', dim: '昏暗', direct: '直接', double: '双重', dress: '连衣裙',
  even: '均匀', expression: '表情', eye: '眼睛', eyes: '眼睛', face: '脸部', flower: '花朵',
  focus: '重点', floral: '花卉', footwear: '鞋履', full: '全身', girl: '女孩', gold: '金色',
  golden: '金色', hair: '头发', hall: '大厅', hand: '手', hands: '双手', high: '高',
  jacket: '外套', lecture: '讲堂', light: '光线', lighting: '光照', long: '长',
  looking: '看向', low: '低', maid: '女仆', medium: '中景', morning: '早晨', natural: '自然',
  night: '夜晚', notes: '笔记', official: '官方', one: '一件', open: '打开', outfit: '服装',
  pants: '长裤', pantyhose: '连裤袜', pillow: '枕头', pink: '粉色', portrait: '肖像',
  proportions: '比例', qipao: '旗袍', red: '红色', reserved: '克制', ribbon: '发带', room: '房间',
  school: '学校', scene: '场景', seat: '座位', shirt: '衬衫', shot: '镜头',
  shy: '害羞', side: '侧面', simple: '简单', sky: '天空', skirt: '裙子', slit: '开衩',
  small: '小型', soft: '柔和', standing: '站立', summer: '夏日',
  trim: '饰边', uniform: '制服', university: '大学', viewer: '镜头', warm: '暖色', white: '白色',
  wide: '广角', window: '窗边', with: '搭配', yellow: '黄色',
  // 高频补充（绘制台常用词条）
  blush: '脸红', smile: '微笑', gentle: '温柔', sad: '失落', angry: '生气',
  surprised: '惊讶', shy_look: '害羞神情',
  tears: '眼泪', crying: '哭泣', laughing: '大笑', wink: '眨眼',
  waiting: '等待', walking: '走路', running: '奔跑', sitting: '坐着', lying: '躺着', kneeling: '跪坐',
  leaning: '倚靠', jumping: '跳跃', sleeping: '睡觉', eye_contact: '眼神接触', feeding: '喂食',
  hugging: '拥抱', resting: '休息', stretching: '伸展', umbrella: '雨伞',
  backpack: '背包', handbag: '手袋', holding_item: '手持物品', holding_cup: '端着杯子',
  holding_book: '拿着书', books: '书本', papers: '文件',
  afternoon: '午后', evening: '傍晚', noon: '正午', sunrise: '日出',
  weather: '天气', rain: '雨', rainy: '下雨', snow: '雪', snowing: '下雪', cloudy: '多云',
  storm: '暴风雨', thunder: '雷', lightning: '闪电', fog: '雾', mist: '薄雾', wind: '风',
  breeze: '微风', cloud: '云', clouds: '云朵', moonlight: '月光', stars: '星星', starry: '星空',
  petals: '花瓣', blossom: '花朵', sakura: '樱花', cherry: '樱花', autumn: '秋天', winter: '冬天',
  fireworks: '烟花', lantern: '灯笼', candle: '蜡烛',
  candlelight: '烛光', neon: '霓虹', bright: '明亮', shadow: '阴影', shadows: '阴影',
  glow: '微光', sparkle: '闪光', sparkles: '闪光', gradient: '渐变',
  neon_lighting: '霓虹灯光', colorful: '多彩', purple: '紫色', violet: '紫罗兰', lavender: '薰衣草色',
  silver: '银色', gray: '灰色', grey: '灰色', green: '绿色', blonde: '金色',
  brunette: '棕发', twintails: '双马尾', ponytail: '单马尾', braid: '辫子', ahoge: '呆毛',
  bangs: '刘海', fringe: '刘海', hairclip: '发夹', hairpins: '发卡', hair_ornament: '发饰',
  loose_hair: '散发', wet_hair: '湿发', straight_hair: '直发', curly_hair: '卷发',
  pleated: '百褶', plaid: '格纹', striped: '条纹', blazer: '西装外套', sailor: '水手服',
  serafuku: '水手服', cardigan: '开衫', turtleneck: '高领', sweater: '毛衣', hoodie: '连帽卫衣',
  coat: '外套', trench_coat: '风衣', fur: '毛皮', kimono: '和服', yukata: '浴衣', furisode: '振袖',
  cheongsam: '旗袍', hanbok: '韩服', swimsuit: '泳装', bikini: '比基尼', pajamas: '睡衣',
  sleepwear: '睡衣', nightgown: '睡裙', bath_towel: '浴巾', miko: '巫女',
  shrine: '神社', temple: '寺庙', park: '公园', garden: '花园', rooftop: '天台', balcony: '阳台',
  hallway: '走廊', corridor: '走廊', library: '图书馆', kitchen: '厨房', dining: '餐厅',
  onsen: '温泉', bath: '浴室', bathroom: '浴室', train: '电车', station: '车站', bus: '公交',
  street: '街道', road: '道路', river: '河流', bridge: '桥', forest: '森林', mountain: '山',
  sea: '大海', pool: '泳池', gymnasium: '体育馆', arcade: '游戏厅',
  convenience_store: '便利店', supermarket: '超市', greenhouse: '温室', music_room: '音乐教室',
  piano: '钢琴', telescope: '望远镜', observatory: '天文台', clock: '时钟', phone: '手机',
  bench: '长椅', swing: '秋千', slide: '滑梯', ferris_wheel: '摩天轮', rooftop_garden: '屋顶花园',
  autumn_leaves: '秋叶', maple: '枫叶', ivy: '常春藤', grass: '草地', field: '田野',
  hill: '山坡', waterfall: '瀑布', pond: '池塘', fountain: '喷泉', snowman: '雪人',
  icicle: '冰凌', frost: '霜', dew: '露珠', rainbow: '彩虹', aurora: '极光', galaxy: '银河',
} as const

const GENERIC_MEANINGS = new Set(['场景词条', '场景成人词', 'v18 训练服装词'])

// WD14 反推高频词条中英词典（2026-08-29 新增，同 chunk 懒加载）。
import { WD14_ZH } from './tagMeaningZh'

function cleanTag(tag: string): string {
  let raw = String(tag || '')
    .replace(/^\s*<lora:|>\s*$/gi, '')
    .trim()
  // 仅当整词被括号整体包裹时才剥括号（如 (masterpiece:1.2) 加权语法）；
  // WD14 角色词尾的 (fate)/(genshin_impact) 等括号是词条的一部分，不能剥。
  if (/^\(.+\)$/.test(raw)) raw = raw.replace(/^\(+|\)+$/g, '')
  raw = raw.replace(/:\s*-?\d+(?:\.\d+)?\s*$/g, '')
  return raw.toLowerCase().replace(/[\s\-/]+/g, '_')
}

const PREPOSITION_WORDS = new Set([
  'of', 'on', 'at', 'in', 'the', 'a', 'an', 'to', 'for', 'with', 'from', 'by', 'into', 'under', 'over', 'behind',
])

function formatNaturalTitle(tag: string): string {
  const words = cleanTag(tag).split('_').filter(Boolean)
  if (!words.length) return String(tag || '').trim()
  return words.map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')
}

/** Returns the catalog Chinese label when present, otherwise a readable token glossary. */
export function tagMeaning(tag: string, catalogLabel = ''): string {
  const supplied = String(catalogLabel || '').trim()
  if (supplied && !GENERIC_MEANINGS.has(supplied)) return supplied

  const normalized = cleanTag(tag)
  if (EXACT_MEANINGS[normalized]) return EXACT_MEANINGS[normalized]

  // WD14 反推高频词整词命中（2026-08-29）：只做整词精确匹配，不参与逐词回退
  if (WD14_ZH[normalized]) return WD14_ZH[normalized]

  // 整词优先：词表里的复合词（convenience_store、winter_coat…）先整体命中，
  // 否则回退到逐词翻译
  if (WORD_MEANINGS[normalized]) return WORD_MEANINGS[normalized]

  const words = normalized.split('_').filter(Boolean)
  // 如果包含介词短语（如 depth_of_field、standing_on_tiptoe 等未在精选表收录的短语），
  // 逐词直接拼接必然导致机翻车祸，此时优雅回退为自然英文标题
  const hasPreposition = words.some(w => PREPOSITION_WORDS.has(w))
  if (hasPreposition) {
    return formatNaturalTitle(tag)
  }

  const translated = words.map(word => WORD_MEANINGS[word])
  const translatedCount = translated.filter(Boolean).length
  // 只有当所有实词均有翻译，或者词数<=3且未翻译单词仅1个时，才进行“ · ”平滑拼接
  if (translatedCount === words.length || (words.length <= 3 && translatedCount >= words.length - 1 && translatedCount >= 1)) {
    return translated.map((meaning, index) => meaning || words[index]).join(' · ')
  }

  return formatNaturalTitle(tag)
}
