'use strict';
/**
 * routes/anima/constants.js —— 纯标量常量（2026-08-27 P1-b 自 anima.js 切出，文本未改）。
 */
var MAX_BODY = '64kb';
var MAX_PENDING = 4;
var MAX_PROMPT_LENGTH = 12000;
var MAX_NEGATIVE_LENGTH = 8000;
var MAX_IMAGE_BYTES = 16 * 1024 * 1024;
var INPUT_IMAGE_TTL_MS = 60 * 60 * 1000;
var JOB_TIMEOUT_MS = 10 * 60 * 1000;
var POLL_INTERVAL_MS = 500;
var JOB_TTL_MS = 30 * 60 * 1000;
var CANCEL_POLL_INTERVAL_MS = 250;
var CANCEL_TIMEOUT_MS = 30 * 1000;
var OUTPUT_NODE_ID = '10';
var OUTPUT_FILENAME_PREFIX = 'anima_app';
module.exports = {
    MAX_BODY: MAX_BODY,
    MAX_PENDING: MAX_PENDING,
    MAX_PROMPT_LENGTH: MAX_PROMPT_LENGTH,
    MAX_NEGATIVE_LENGTH: MAX_NEGATIVE_LENGTH,
    MAX_IMAGE_BYTES: MAX_IMAGE_BYTES,
    INPUT_IMAGE_TTL_MS: INPUT_IMAGE_TTL_MS,
    JOB_TIMEOUT_MS: JOB_TIMEOUT_MS,
    POLL_INTERVAL_MS: POLL_INTERVAL_MS,
    JOB_TTL_MS: JOB_TTL_MS,
    CANCEL_POLL_INTERVAL_MS: CANCEL_POLL_INTERVAL_MS,
    CANCEL_TIMEOUT_MS: CANCEL_TIMEOUT_MS,
    OUTPUT_NODE_ID: OUTPUT_NODE_ID,
    OUTPUT_FILENAME_PREFIX: OUTPUT_FILENAME_PREFIX,
};
