'use strict';

/**
 * routes/anima/constants.js —— 纯标量常量（2026-08-27 P1-b 自 anima.js 切出，文本未改）。
 */


let MAX_BODY = '64kb';
let MAX_PENDING = 4;
let MAX_PROMPT_LENGTH = 12000;
let MAX_NEGATIVE_LENGTH = 8000;
let MAX_IMAGE_BYTES = 16 * 1024 * 1024;
let INPUT_IMAGE_TTL_MS = 60 * 60 * 1000;
let JOB_TIMEOUT_MS = 10 * 60 * 1000;
let POLL_INTERVAL_MS = 500;
let JOB_TTL_MS = 30 * 60 * 1000;
let CANCEL_POLL_INTERVAL_MS = 250;
let CANCEL_TIMEOUT_MS = 30 * 1000;
let OUTPUT_NODE_ID = '10';
let OUTPUT_FILENAME_PREFIX = 'anima_app';

export = {
  MAX_BODY:MAX_BODY,
  MAX_PENDING:MAX_PENDING,
  MAX_PROMPT_LENGTH:MAX_PROMPT_LENGTH,
  MAX_NEGATIVE_LENGTH:MAX_NEGATIVE_LENGTH,
  MAX_IMAGE_BYTES:MAX_IMAGE_BYTES,
  INPUT_IMAGE_TTL_MS:INPUT_IMAGE_TTL_MS,
  JOB_TIMEOUT_MS:JOB_TIMEOUT_MS,
  POLL_INTERVAL_MS:POLL_INTERVAL_MS,
  JOB_TTL_MS:JOB_TTL_MS,
  CANCEL_POLL_INTERVAL_MS:CANCEL_POLL_INTERVAL_MS,
  CANCEL_TIMEOUT_MS:CANCEL_TIMEOUT_MS,
  OUTPUT_NODE_ID:OUTPUT_NODE_ID,
  OUTPUT_FILENAME_PREFIX:OUTPUT_FILENAME_PREFIX,
};
