#!/usr/bin/env node
'use strict';

/**
 * scripts/workflow.js — 统一工作流入口
 *
 * 解决：maintenance 脚本分散、入口难发现、参数不统一。
 * 用法：
 *   node scripts/workflow.js --help
 *   node scripts/workflow.js <group> --help
 *   node scripts/workflow.js <group>:<action> [options]
 *   npm run workflow -- <group>:<action> [options]
 *
 * 设计：薄封装，不接管业务逻辑，仅做发现、校验与转发，
 * 保持对现有脚本的完全兼容（直接 node 旧脚本仍可用）。
 *
 * 运行条件元数据（计划 006 W1，2026-09-13）：
 *   每个注册项的 run 字段是 help / plan / audit:workflows 共用的结构化描述，
 *   只用于展示与审计，runner 不据此拦截或改写执行（无运行时策略）。
 *   - nature：默认（不带开关）行为的 facet，多值；枚举见 scripts/lib/workflow-runner.js EFFECTS
 *   - machine：运行环境要求，多值；枚举见 MACHINES
 *   - switches：显式开关改变的行为（值同样用 EFFECTS）；runner 级 --plan/--help 不在此列
 *   - resume：idempotent（重跑覆盖/等价）| checkpoint（按已完成条目断点续跑）| na
 *   - evidence：结论的核实位置（文件:行）；unknown：未核实点，不猜
 *   - notes：已确证但待主任务处理的缺陷登记（不改执行）
 *   复合（steps）工作流的 nature 必须覆盖各子步骤，不得只标 read-only；
 *   audit:workflows 校验以上全部约束。
 */

const path = (require('path') as typeof import('path'));

const ROOT = path.resolve(__dirname, '..');

const WORKFLOWS: import('./lib/workflow-types').RegisteredWorkflows = {
  'content:catalog': { desc: '记录式内容库：整位角色、记录/历史读取、局部快照合并导出与字段补丁；patch/import 默认预览', cmd: ['node', 'scripts/maintenance/run-rust-runtime.js', 'catalog'], opts: '<stats|query|record|history|character|export|patch|import|check|colors> [--root <项目目录>] --runtime-root <运行目录> [--kind <类型> --id <ID> --revision <修订>] [--character <ID> ...] [--record <kind:id> ...] [--created-from <RFC3339> --created-to <RFC3339>] [--sort <排序> --page <页> --page-size <数量>] [--file <JSON>] [--out <导出目录>] [--apply]', docs: 'docs/maintenance.md',
    run: { nature: ['preview', 'self-heal-missing'], machine: ['node'], switches: { '--apply': ['writes-product'] }, resume: 'na', evidence: 'runtime-rs/src/catalog/cli.rs', notes: ['需要 Rust/Cargo；首次使用会初始化工作内容库；export 会显式写出 --out 指定的快照目录。'], unknown: ['不执行模型调用或安装；快照不恢复跨机器的本机修订历史'] } },
  'live2d:sync-local': {
    desc: '个人桌面同步已核验本机模型，保留目标旧版本；不进入安装包',
    cmd: ['node', 'scripts/maintenance/sync-local-live2d.js'], required: ['--source', '--target'],
    opts: '--source <本机导入根> --target <本机目标根> [--apply]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product'] }, resume: 'idempotent',
      evidence: 'scripts/maintenance/sync-local-live2d.ts:1', unknown: ['目标桌面运行时验收'], notes: ['先核验所有源哈希；只同步已登记依赖，保留旧目标版本'] },
  },
  'live2d:import-candidates': {
    desc: '核对并导入本机 Live2D 候选；默认预览，原件不变，不发布或安装',
    cmd: ['node', 'scripts/maintenance/import-live2d-candidates.js'],
    opts: '[--root <项目根>] [--ids <逗号分隔角色ID>] [--apply] [--refresh 保留旧版本后更新]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product'], '--refresh': ['writes-product'] }, resume: 'idempotent',
      evidence: 'scripts/maintenance/import-live2d-candidates.ts:1', unknown: ['原生后端与音频设备验收'],
      notes: ['只生成 runtime/live2d-imports 本机副本，拒绝覆盖不同内容；不解包 lpk，不上传或发布'] },
  },
  ...(require('./lib/workflows-content-checks') as typeof import('./lib/workflows-content-checks')),
  'tags:untranslated': { desc: '按现行离线释义统计本地 PixAI 结果或 WD14 CSV 的待补中文词条', cmd: ['node', 'scripts/tests/extract-wd14-untranslated.js'], required: ['--input'],
    opts: '--input <PixAI JSON/JSONL 或 WD14 CSV> [--general-top <n>] [--character-top <n>] [--json]', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/extract-wd14-untranslated.ts', unknown: ['统计限输入样本；部分中文与英文回退不代表准确翻译'], notes: ['只读取本地文件并输出清单；不上传、不翻译、不写词典；PixAI 置信度不计为频次'] } },
  ...(require('./lib/workflows-diagnostics') as typeof import('./lib/workflows-diagnostics')),
  'maintenance:recover': {
    desc: '预览已中断维护事务的精确文件恢复；显式apply绑定预览后执行',
    cmd: ['node', 'scripts/maintenance/run-rust-runtime.js', 'recover'], required: ['--root', '--runtime-root'], docs: 'docs/workflow.md#rust-运行时迁移',
    opts: '--root <绝对项目根> --runtime-root <绝对运行目录> [--showcase-root <可信样张根>] [--backup-id <备份ID>] [--out <新预览文件>] [--apply-plan <保存的签名预览JSON>]',
    run: { nature: ['read-only', 'preview'], machine: ['node'], switches: { '--apply-plan': ['writes-source', 'writes-product', 'delete', 'guard'], '--out': ['writes-product'] },
      resume: 'checkpoint', evidence: 'runtime-rs/src/maintenance/cli.rs:1',
      unknown: ['实际断电、磁盘故障和主力机恢复仍需设备验收'],
      notes: ['活进程/未知锁不抢占；预览绑定源根、journal和文件状态；只恢复声明目标，保留恢复前备份；失败保持拒绝读写'] },
  },
  'audit:workflow-conditions': { desc: '只读运行条件与复合副作用覆盖报告', cmd: ['node', 'scripts/maintenance/report-workflow-conditions.js'],
    opts: '--json；--root <隔离目录>；--domain <工作流分组>', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/report-workflow-conditions.js:1', unknown: ['元数据与路径存在性不证明实际执行成功'] } },
  'audit:ownership': { desc: '只读内容归属报告：权威源、派生文件与读写边界', cmd: ['node', 'scripts/maintenance/report-content-ownership.js'],
    opts: '--json；--consistency；--root <隔离目录>；--domain <characters|popular|scenes|blueprints|curation|retired|references|themes|showcase>', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--json': ['read-only'], '--consistency': ['read-only', 'guard'] }, resume: 'na', evidence: 'scripts/maintenance/report-content-ownership.js:1', unknown: ['默认浅层结构与职责；--consistency 核对已实现的源/产物投影，未覆盖字段保持 unknown；内容、图片质量及外部样张未验收'] } },
  'capture:delivery': { desc: '捕获交付输入、绑定实际结果及最终提交；默认只读输出', cmd: ['node', 'scripts/maintenance/capture-delivery.js'],
    opts: '--scope <说明> --source-file/tree <路径> --build-file/tree <路径>；或 --baseline <证据JSON> [--record <结果JSON>] [--machine office|main] [--finalize-commit <完整SHA>]；--gate <字段=source,build>；--save <runtime/delivery-evidence/新文件.json>；--root <根>；--json', docs: 'docs/workflow.md',
    needs: 'Node；提交身份核验需要本地 Git；结果与日志必须来自实际执行',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--save': ['writes-product'], '--finalize-commit': ['read-only', 'guard'] }, resume: 'na', evidence: 'scripts/maintenance/capture-delivery.js:1', unknown: ['只绑定明确选择的输入、构建与日志字节；不执行门禁，不认证日志语义，不替代安装、模型和设备验收'], notes: ['--save 仅新建专用证据，拒绝覆盖；最终提交关联保留执行前 HEAD'] } },
  'audit:delivery': { desc: '只读交付证据审计：比较交付标识，区分错误与待验', cmd: ['node', 'scripts/maintenance/audit-delivery.js'],
    opts: '--evidence <JSON>；--compare-evidence <root内相对JSON路径>（可重复）；--require <gate.path>（可重复）；--expect-commit <SHA>；--check-head（需本地 Git，只比较 HEAD commit，不覆盖 dirty working tree，不查询远端）；--check-worktree（需本地 Git，独立检查未提交/未跟踪文件，dirty 或不可用退出 1）；--expect-build <field=SHA256>（可重复）；--verify-file <相对root路径>（可重复）；--expect-file-sha256 <相对root路径=64位SHA256>（可重复）；--root <隔离目录>；--json', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--json': ['read-only'], '--check-head': ['read-only'], '--check-worktree': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/audit-delivery.js:1', unknown: ['自动重算 tracking 的选定输入/构建/日志，变化使相关通过项 stale；旧无 tracking 通过项为 unknown；不证明日志语义或真实设备/模型验收'] } },
  'audit:impact': { desc: '只读变更影响报告：角色/服装、场景与显式路径；未知范围单列', cmd: ['node', 'scripts/maintenance/report-content-impact.js'],
    opts: '--character <id> [--outfit <id>] 或 --scene <scNNN/sc1000+> 或 --path <仓库相对路径>（可重复）；--git-diff；--base <本地commit/ref>；--showcase-manifest <root内相对路径>（可重复）；--root <隔离目录>；--json', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--json': ['read-only'], '--base': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/report-content-impact.js:1', unknown: ['历史对照保留删除/重命名及旧新关系；增量检查仅输出计划，未知/公共约束仍需 full；真实内容和设备未验收'] } },
  'audit:resource-manifest': { desc: '只读本地资源清单生成、校验与差异比较：root/assets 路径、字节、SHA-256，零写入', cmd: ['node', 'scripts/maintenance/report-resource-manifest.js'],
    opts: '--root <目录>；--manifest <root内JSON>（校验模式：重复/非法/越界路径、缺失、字节与哈希）；--manifest <旧JSON> --compare-manifest <新JSON>（差异比较：按精确路径输出新增/移除/改变/未改变，只读两份清单不读实际资产）', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--manifest': ['guard'], '--compare-manifest': ['guard'] }, resume: 'na', evidence: 'scripts/maintenance/report-resource-manifest.js:1', unknown: ['哈希一致只证明字节相同；文件存在不代表内容已交付、图片质量或审核通过；校验只核对已列条目，不发现未登记文件；差异比较不含未核验项与结构错误时才可宣称已列条目一致，仍不证明目录覆盖完整或内容已审核'] } },
  'offline:assistant': { desc: '打开本地 ZIP 图形安装助手；自动校验，用户确认后调用原生导入', cmd: ['powershell.exe', '-NoProfile', '-STA', '-WindowStyle', 'Hidden', '-ExecutionPolicy', 'Bypass', '-File', 'tools/offline-resource-assistant.ps1'], docs: 'docs/guides/offline-resources.md',
    run: { nature: ['writes-product'], machine: ['windows'], switches: {}, resume: 'idempotent', evidence: 'tools/offline-resource-assistant.ps1; tools/install-offline-resources.ps1', notes: ['默认执行打开可写安装助手；校验通过并由用户确认退出及安装后才写入。工作流 --help/--plan 只显示入口信息，不启动助手或安装。'], unknown: ['只接受内置受信发行；需要配套支持取消通道的原生程序；实际安装另验'] } },
  'offline:pack': { desc: '离线素材候选发行：完整包或基于旧发行的增量 ZIP，只复制新增/变化资源与样张；带校验指纹和无 Node 的图形安装入口，默认预览', cmd: ['node', 'scripts/maintenance/stage-offline-release.js'], required: ['--showcase-root', '--release', '--out'],
    opts: '--showcase-root <已发布样张目录> --release <安全版本ID> --out <新输出父目录> [--root <项目根>] [--base-release <旧release.json>] [--apply]', docs: 'docs/guides/offline-resources.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product'] }, resume: 'na', evidence: 'scripts/maintenance/stage-offline-release.ts', unknown: ['真实画面/设备与公开来源审批另验；不含推理权重和私有参考；--apply 仅 Windows，输出不覆盖'] } },
  'offline:prerequisites-plan': { desc: '只读预览微软 VC++ x64 离线前置材料；不下载、不安装', cmd: ['powershell.exe', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', 'scripts/maintenance/prepare-offline-prerequisites.ps1'], required: ['-Out'], opts: '-Out <新目录>', docs: 'docs/guides/offline-resources.md',
    run: { nature: ['read-only'], machine: ['windows'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/prepare-offline-prerequisites.ps1', unknown: [] } },
  'offline:prerequisites-prepare': { desc: '准备微软 VC++ x64 离线安装材料，验证有效微软签名并记录哈希/版本；不执行安装', cmd: ['powershell.exe', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', 'scripts/maintenance/prepare-offline-prerequisites.ps1', '-Apply'], required: ['-Out'], opts: '-Out <新目录>', docs: 'docs/guides/offline-resources.md',
    run: { nature: ['network-download', 'writes-product'], machine: ['windows', 'network'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/prepare-offline-prerequisites.ps1', unknown: ['目标机器安装、UAC及真实原生功能另验'], notes: ['仅官方下载和验签；不安装，不覆盖旧材料，失败保留独立暂存'] } },
  'resource:pack': { desc: '离线资源候选包暂存导出：默认预览零写入；--apply 经清单核验后复制到 root 内新候选目录（不覆盖旧包，不是发布/安装入口）；--base-manifest 增量模式只复制差异项', cmd: ['node', 'scripts/maintenance/stage-resource-pack.js'],
    opts: '--manifest <root内JSON> --name <包名>；[--base-manifest <root内旧JSON>]（与 --manifest 同用：增量候选，只复制 added/changed，写 manifest.json 与 delta.json，不是完整可安装包）；--root <目录>；--apply（仅 Windows 实际复制；其他平台可预览）', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product'], '--base-manifest': ['guard'] }, resume: 'na', evidence: 'scripts/maintenance/stage-resource-pack.js:1', unknown: ['候选包通过字节核验仅表示复制内容与清单一致，不代表图片质量、审核或部署完成；目标必须不存在（不覆盖旧包），写入范围限 --root 内 scripts/archive/resource-packs；预览仍会读取清单与源文件；增量候选只含差异项，不是完整可安装包，不能当作已安装更新'] } },
  'resource:verify-delta': { desc: '只读增量候选包与基线兼容核验：结构/身份/数量重算与候选实际字节，全程零写入', cmd: ['node', 'scripts/maintenance/verify-resource-pack.js'],
    opts: '--base-manifest <root内JSON> --pack <root内候选目录>；--root <目录>', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/verify-resource-pack.js:1', unknown: ['核验通过仅表示相对于给定基线可重建声明目标且候选已列字节匹配；不是数字签名、可信来源、当前安装状态或质量验收；不发现候选包未登记文件；基线资产不被读取（removed 文件可已不存在）'] } },
  'resource:install': { desc: '导入已审批的离线/已下载资源包；默认预览', cmd: ['node', 'scripts/maintenance/manage-resource-install.js', 'import'], required: ['--config', '--release'],
    opts: '--config <可信本地JSON> --release <已配置ID> [--apply]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product', 'delete'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/manage-resource-install.js:1', unknown: ['程序/页面接线及真实安装升级待验收'], notes: ['仅写专用用户资源库；清理仅本工具暂存文件；保留旧版本和用户作品；哈希不替代来源审批'] } },
  'resource:download': { desc: '下载已审批来源的候选资源包，可取消/续传；默认预览', cmd: ['node', 'scripts/maintenance/manage-resource-install.js', 'download'], required: ['--config', '--release'],
    opts: '--config <可信本地JSON> --release <已配置ID> [--apply]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['network-download', 'writes-product', 'delete'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/manage-resource-install.js:1', unknown: ['真实托管/带宽和资源审核待确定'], notes: ['--apply 需要已审批网络来源；下载不自动安装；仅清理本工具暂存文件'] } },
  'resource:recover': { desc: '恢复专用资源库未完成事务；默认预览', cmd: ['node', 'scripts/maintenance/manage-resource-install.js', 'recover'], required: ['--config'],
    opts: '--config <可信本地JSON> [--apply]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product', 'delete'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/manage-resource-install.js:1', unknown: ['仅隔离进程中断验证，断电和真实设备仍待验收'] } },
  'resource:rollback': { desc: '恢复已保留的上一资源版本；默认预览', cmd: ['node', 'scripts/maintenance/manage-resource-install.js', 'rollback'], required: ['--config'],
    opts: '--config <可信本地JSON> [--apply]', docs: 'docs/workflow.md',
    run: { nature: ['preview', 'read-only'], machine: ['node'], switches: { '--apply': ['writes-product', 'delete'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/manage-resource-install.js:1', unknown: ['必须有可核验旧版本；不回滚应用或用户作品'] } },
  'resource:installed': { desc: '核对专用资源库已安装字节及待恢复状态', cmd: ['node', 'scripts/maintenance/manage-resource-install.js', 'status'], required: ['--config'],
    opts: '--config <可信本地JSON>', docs: 'docs/workflow.md',
    run: { nature: ['guard', 'writes-product', 'delete'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/lib/resource-install.js:1', unknown: ['状态核验会获取并释放专用锁，不是零写入审计；不证明图片质量'] } },
  'showcase:review-sheets': { desc: '从候选审核目录生成逐图查看用联系表', cmd: ['python', 'scripts/maintenance/build-scene-manual-audit-sheets.py'], required: ['--audit'], docs: 'docs/workflow.md',
    run: { nature: ['writes-product'], machine: ['python-pillow'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/build-scene-manual-audit-sheets.py:134-162', unknown: [], notes: ['输出写在 --audit 目录下，通常在仓库外'] } },
  'showcase:manual-review': { desc: '汇总明确人工决定；缺少决定的图片保持 pending', cmd: ['node', 'scripts/maintenance/build-scene-manual-review.js'], required: ['--manifest', '--decisions'], docs: 'docs/workflow.md',
    run: { nature: ['writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/build-scene-manual-review.js:41-66', unknown: [] } },
  'showcase:scene-publish': { desc: '旧独立场景发布器：校验逐图审核后预览；--apply 写新版本', cmd: ['node', 'scripts/maintenance/publish-scene-showcase-anima11.js'], required: ['--from', '--source', '--target'], docs: 'docs/workflow.md',
    run: { nature: ['preview'], machine: ['node', 'python-pillow'], switches: { '--apply': ['writes-release'], '--force': ['delete', 'writes-release'] }, resume: 'idempotent', evidence: 'scripts/maintenance/publish-scene-showcase-anima11.js:506-509,511-555', unknown: [] } },
  'showcase:rating-refresh': { desc: '仅刷新发布清单分级，默认预览；--apply 写新版本', cmd: ['node', 'scripts/maintenance/publish-rating-refresh.js'], required: ['--source', '--target'], docs: 'docs/workflow.md',
    run: { nature: ['preview'], machine: ['node'], switches: { '--apply': ['writes-release'], '--force': ['delete', 'writes-release'] }, resume: 'idempotent', evidence: 'scripts/maintenance/publish-rating-refresh.js:193-213', unknown: [] } },
  'reference:repair-urls': { desc: '参考 URL 迁移修复并备份；先传 --dry-run 核对清单', cmd: ['node', 'scripts/maintenance/repair-character-reference-urls.js'], docs: 'docs/workflow.md',
    run: { nature: ['writes-source'], machine: ['node'], switches: { '--dry-run': ['preview'] }, resume: 'idempotent', evidence: 'scripts/maintenance/repair-character-reference-urls.js:80,139-142,191-192', unknown: [] } },
  'models:download-h3': { desc: '下载 H3 当前工作流的六项可选模型（约 43.99 GB / 40.97 GiB），逐项字节和 SHA-256 校验', cmd: ['node', 'scripts/maintenance/download-minimax-h3.js'], required: ['--models-root'], docs: 'docs/guides/setup-and-models.md',
    opts: '--models-root <实际ComfyUI/models目录>；--plan仅打印固定文件、来源与校验值',
    run: { nature: ['network-download', 'writes-product'], machine: ['node', 'network'], switches: { '--plan': ['preview', 'read-only'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/download-minimax-h3.ts', unknown: ['文件校验不证明节点、cu130和设备能推理'], notes: ['固定官方来源revision与SHA-256；中断文件从零重下，已完成文件重新校验后复用；Ctrl+C取消'] } },
  'models:check': { desc: '只读检查硬件清单、模型文件与 PixAI 配置路径，不执行推理', cmd: ['node', 'scripts/maintenance/check-models-environment.js'], docs: 'docs/guides/setup-and-models.md',
    opts: '[--json] [--verify-hashes] 显式读取已知权重校验 SHA-256',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--verify-hashes': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/check-models-environment.ts', unknown: ['Python 包可导入性与版本、CUDA/BF16、真实推理和设备性能'], notes: ['PixAI 按网关回执优先级与环境变量选择目录；默认仅检查文件及已知长度，--verify-hashes 会读取大文件；不加载模型、启动服务或安装依赖'] } },
  'models:download-wd14': { desc: '下载 WD14 MOAT v2（ONNX 约 311 MiB＋CSV），固定字节与 SHA-256 校验', cmd: ['node', 'scripts/maintenance/download-wd14.js'], opts: '--target-dir <可写目录>；--official（默认）、--modelscope、--mirror三选一；--plan零下载', docs: 'docs/guides/setup-and-models.md',
    run: { nature: ['network-download', 'writes-product'], machine: ['node', 'network'], switches: { '--plan': ['preview', 'read-only'], '--mirror': ['network-download'], '--official': ['network-download'], '--modelscope': ['network-download'] }, resume: 'idempotent', evidence: 'scripts/maintenance/download-wd14.ts', unknown: ['原生DLL与真实推理另验'], notes: ['默认固定HuggingFace发布者版本；镜像内容也必须匹配同一SHA-256；多个来源开关拒绝；Ctrl+C取消'] } },
  'models:prepare-pixai': { desc: '准备固定 PixAI v1.0 与独立 timm 依赖；不修改现有 Comfy/Python', cmd: ['node', 'scripts/maintenance/prepare-pixai.js'], opts: '--target-dir <可写runtime根>；--python <已有Python>；--torch-site-packages <已有torch包目录>；--reuse-from <已下载候选根>；--plan零写入；--check本机只读核验', docs: 'docs/workflow.md#pixai-本机反推准备',
    run: { nature: ['network-download', 'writes-product'], machine: ['node', 'network'], switches: { '--plan': ['preview', 'read-only'], '--check': ['read-only', 'guard'] }, resume: 'idempotent', evidence: 'scripts/maintenance/prepare-pixai.ts', unknown: ['准备不执行GPU推理；目标设备显存与真实模型另验'], notes: ['复用已验证权重；仅向独立target/deps安装固定timm；不会启动Comfy或修改既有环境', '--check默认复用目标回执的Python/Torch路径，显式参数和环境变量优先；坏回执拒绝且不改写；--plan不读取目标回执'] } },
  'desktop:verify-gateway': { desc: '按安装包资源映射隔离验证网关和桌宠页面', cmd: ['node', 'scripts/maintenance/verify-desktop-gateway.js'], docs: 'docs/desktop-deployment.md',
    run: { nature: ['isolated-fixture', 'service'], machine: ['windows', 'node'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/verify-desktop-gateway.js:47-85', unknown: [] } },
  'desktop:doctor': { desc: '检查 Windows 桌面打包工具链与 Cubism SDK', cmd: ['node', 'scripts/maintenance/desktop-build-environment.js'], docs: 'docs/desktop-deployment.md',
    run: { nature: ['read-only'], machine: ['windows', 'node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/desktop-build-environment.js:39-64', unknown: [] } },
  'desktop:storage-benchmark': { desc: '用临时库和私有浏览器比较 IndexedDB 与 SQLite 原型，不访问用户数据', cmd: ['node', 'scripts/tests/prototypes/benchmark-artwork-storage.js'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture'], machine: ['node', 'playwright-browser'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/prototypes/benchmark-artwork-storage.js:56-135', unknown: [] } },
  'desktop:rust-bundle': { desc: '在仓库外隔离布局验证已暂存的 Rust gateway 与原生依赖', cmd: ['node', 'scripts/tests/test-rust-bundle.js'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture', 'service'], machine: ['windows', 'node', 'build-present'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/test-rust-bundle.ts', unknown: ['真实模型与最终安装另验'], notes: ['先准备当前Rust release与staging；真实bundle映射进入临时目录，模型上游隔离，不下载、不安装、不访问用户库'] } },
  'rust:check': { desc: '检查 Rust runtime 格式、Clippy 与隔离行为测试', cmd: ['node', 'scripts/maintenance/run-rust-runtime.js', 'check'], docs: 'docs/workflow.md#rust-运行时迁移',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/run-rust-runtime.ts', unknown: ['需要 Rust 工具链；首次可能下载锁定 crate'], notes: ['不连接生产库，不调用模型，不安装'] } },
  'rust:build': { desc: '构建锁定依赖的 Rust release runtime，不安装', cmd: ['node', 'scripts/maintenance/run-rust-runtime.js', 'build'], docs: 'docs/workflow.md#rust-运行时迁移',
    run: { nature: ['writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/run-rust-runtime.ts', unknown: ['需要 Rust 工具链；首次可能下载锁定 crate'] } },
  'rust:parity': { desc: '隔离比较 Node/Rust 工作区 HTTP、旧回执和读取时延', cmd: ['node', 'runtime-rs/tests/parity.mjs'], docs: 'docs/workflow.md#rust-运行时迁移',
    run: { nature: ['isolated-fixture', 'service'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'runtime-rs/tests/parity.mjs', unknown: [], notes: ['先 build:runtime 和 rust:build；两个独立临时库，顺序测量，不代表全产品性能'] } },
  'rust:licenses:collect': { desc: '按固定配方摘要采集原生依赖的公开源码许可材料', cmd: ['pwsh', '-NoProfile', '-File', 'runtime-rs/native-licenses/collect-sources.ps1'], docs: 'docs/workflow.md#rust-运行时迁移',
    run: { nature: ['network-download', 'writes-product'], machine: ['windows', 'network'], switches: {}, resume: 'idempotent', evidence: 'runtime-rs/native-licenses/collect-sources.ps1', unknown: ['需要 PowerShell 7 和 tar；采集不等于完成发行许可核验'], notes: ['只处理 components.json 列出的公共源码，跳过已核验条目；归档缓存不入 Git；修改材料后必须更新材料清单及根 manifest 摘要'] } },
  'desktop:renderer-process-check': { desc: '使用已有模型在隔离 Windows 进程验证 Live2D 画面、帧率与故障回收', cmd: ['node', 'scripts/tests/test-live2d-renderer-process.mjs'], required: ['--exe', '--assets-root', '--out'],
    opts: '--exe <已构建候选EXE> --assets-root <已有assets目录> --out <新证据目录> [--sample-ms 2000]', docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture', 'writes-product'], machine: ['windows', 'node', 'build-present'], switches: {}, resume: 'na', evidence: 'scripts/tests/test-live2d-renderer-process.mts', unknown: ['不同机器的GPU性能；快照需要实际视觉审查'], notes: ['真实本地GPU与可见隔离窗口；需支持renderer child/probe协议的候选；仅读取已有宁宁和夏目资源，不下载、不调用AI生成、不启动安装版或读取生产profile；与其他GPU测量串行；帧率只记录实测，不把目标值当成达成值'] } },
  'desktop:thumbnail-benchmark': { desc: '隔离测量 1k/10k 历史缩略图预热的前台、后台和双页资源成本', cmd: ['node', 'scripts/tests/prototypes/benchmark-thumbnail-warmup.js'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture'], machine: ['node', 'playwright-browser'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/prototypes/benchmark-thumbnail-warmup.ts', unknown: ['浏览器是否提供真实 hidden 状态'], notes: ['三轮五秒观察；临时同源私有浏览器不访问生产库；独占运行，不与构建或其他浏览器测试并行；输出 JSON，无性能门禁'] } },
  'desktop:restore-benchmark': { desc: '隔离测量真实备份导出、解析和 1k/10k 恢复，不访问用户库', cmd: ['node', 'scripts/tests/prototypes/benchmark-backup-restore.js'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture'], machine: ['node', 'playwright-browser'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/prototypes/benchmark-backup-restore.ts', unknown: ['JS堆采样不代表完整进程峰值或512MiB容量'], notes: ['三轮私有上下文与64张中性PNG；使用真实导出/恢复实现；独占运行，输出JSON，无性能阈值'] } },
  'desktop:package-local': { desc: '跳过压缩生成本机测试安装包', cmd: ['npm', 'run', 'package:tauri', '--', '--config', 'tauri.local.json'], docs: 'docs/desktop-deployment.md',
    run: { nature: ['writes-release'], machine: ['windows', 'windows-toolchain'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.package:tauri; scripts/maintenance/run-tauri.js:17', unknown: [] } },
  'desktop:upgrade-local': { desc: '复用匹配构建，先检查已有安装再仅封装本机轻量升级包',
    cmd: ['node', 'scripts/maintenance/release-desktop-update.js', '--manual', '--skip-build', '--upgrade-only'],
    required: ['--install-dir'], opts: '--install-dir <已有安装目录>', docs: 'docs/desktop-deployment.md',
    run: { nature: ['writes-release'], machine: ['windows', 'windows-toolchain', 'build-present'], switches: {}, resume: 'idempotent',
      evidence: 'scripts/maintenance/release-desktop-update.ts; scripts/lib/desktop-upgrade-installer.ts', unknown: [],
      notes: ['需要匹配当前源码的 NSIS 构建；不重编应用、不封装完整包、不安装或发布；素材不匹配在升级包压缩前拒绝'] } },
  'desktop:content-sync': {
    desc: '同步仍按文件维护的 data 并可选清 WebView2 缓存；不更新记录式内容库（默认只读预览）',
    cmd: ['node', 'scripts/maintenance/sync-desktop-content.js'],
    docs: 'docs/desktop-deployment.md#数据改动如何到达桌面端',
    opts: '[--apply] [--clear-webview-cache] [--content-root=目录] [--source=目录] [--webview-root=目录]',
    run: {
      nature: ['read-only'], machine: ['node', 'windows'],
      switches: { '--apply': ['writes-product'], '--clear-webview-cache': ['delete'] }, resume: 'idempotent',
      evidence: 'scripts/maintenance/sync-desktop-content.ts',
      unknown: ['不重启应用，也不证明应用内画面；安装目录与个人内容目录的差异仍需人工核对'],
      notes: ['本入口不导入快照、不更新 content/catalog.sqlite；人物/服装/场景/蓝图需在内容维护或 content:catalog 中预览并导入快照。仍按文件维护的数据可在此同步；写入或清缓存前需从托盘退出桌面端并释放维护锁，完成后再重启', '只同步桌面打包白名单数据，不复制 history/projects/prompts 等私有状态；覆盖前备份原始字节到 content-sync-backups/<ID>，逐文件原子写入，目标独有项保留并报告', '尊重 AICS_DESKTOP_CONFIG_ROOT 与 AICS_DESKTOP_WEBVIEW_DATA_DIR；拒绝根目录重叠、写入目标链接、陈旧预压缩副本及已检测到的并发修改；失败可能留下已同步文件与备份，不提供整批事务回滚'],
    },
  },
  'brand:build': { desc: '从手绘 SVG 生成字标，从角色头像母图生成网站与桌面图标', cmd: ['node', 'scripts/maintenance/build-brand-assets.js'], docs: 'docs/workflow.md',
    run: { nature: ['writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/maintenance/build-brand-assets.js:17-26', unknown: [] } },
  'docs:check': { desc: '检查文档文件链接与旧地址映射', cmd: ['node', 'scripts/maintenance/check-doc-links.js'], docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/check-doc-links.js:38', unknown: [] } },
  'audit:workflows': { desc: '只读审计注册入口、npm 脚本、文档及复合依赖', builtin: 'audit', docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--json': ['read-only'] }, resume: 'na', evidence: 'scripts/lib/workflow-runner.js:7-21', unknown: [] } },
  'check:workflows': { desc: '工作流执行与门禁路由回归测试', cmd: ['node', 'scripts/tests/test-workflow-runner.js'], docs: 'docs/workflow.md',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/test-workflow-runner.js:13-108', unknown: [] } },
  'check:desktop-deploy': { desc: '隔离验证部署退出前置检查，不停止真实应用或安装', cmd: ['node', 'scripts/tests/test-desktop-deploy-guard.js'], docs: 'docs/desktop-deployment.md',
    run: { nature: ['isolated-fixture'], machine: ['node', 'windows'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/test-desktop-deploy-guard.ts', unknown: ['不触发真实 UAC 或安装器'] } },
  'dev:web': { desc: '启动前端开发服务', cmd: ['npm', 'run', 'dev'], docs: 'docs/workflow.md',
    run: { nature: ['service'], machine: ['node'], switches: {}, resume: 'na', evidence: 'package.json scripts.dev', unknown: [] } },
  'dev:server': { desc: '监视 TypeScript 变更，通过检查后重启网关', cmd: ['npm', 'run', 'dev:server'], docs: 'docs/workflow.md',
    run: { nature: ['service', 'writes-product'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/dev-server.mts', unknown: [], notes: ['检查失败保留上一版网关；源码和产物一致时复用构建；网关仍按原行为自愈缺失数据'] } },
  'office:health': { desc: '检查办公机工程目录与维护入口', cmd: ['node', 'scripts/maintenance/office-health.js'], docs: 'docs/workflow.md',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/office-health.ts', unknown: ['目录存在不代表工具链或真实设备验收通过'] } },
  'check:typescript': { desc: '只读严格检查服务、网关、工具和独立浏览器脚本', cmd: ['node', 'scripts/build-node.mts', '--check'], docs: 'docs/workflow.md',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/build-node.mts', unknown: [] } },
  'check:typescript-build': { desc: '隔离验证 TypeScript 构建、缓存和开发重启行为', cmd: ['node', '--test', 'scripts/tests/test-typescript-build.js', 'scripts/tests/test-typescript-development.js'], docs: 'docs/workflow.md',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'scripts/tests/test-typescript-build.ts; scripts/tests/test-typescript-development.ts', unknown: [] } },
  'installer:modern': {
    desc: '构建现代原生安装器（--preview --capture 可安全预览，不安装）',
    cmd: ['node', 'scripts/maintenance/build-modern-installer.js'],
    docs: 'docs/guides/desktop/game-installer.md',
    run: { nature: ['writes-release'], machine: ['windows', 'windows-toolchain'], switches: { '--preview': ['writes-product'], '--capture': ['writes-product'], '--upgrade': ['writes-release'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-modern-installer.js:10-13,44-70', unknown: ['--capture 截图落盘位置未逐行核实'] },
  },
  'installer:bundle': {
    desc: '用已绑定桌面构建生成完整包与升级包并分别签名（只改安装界面时使用）',
    cmd: ['node', 'scripts/maintenance/release-desktop-update.js', '--bundle-only'],
    docs: 'docs/guides/desktop/game-installer.md',
    run: { nature: ['writes-release'], machine: ['windows', 'windows-toolchain'], switches: { '--publish': ['publish-remote'], '--bump': ['writes-source'] }, resume: 'idempotent', evidence: 'scripts/maintenance/release-desktop-update.js:33-39,76-86,215-242', unknown: [], notes: ['--publish 推送 GitHub Releases（外部发布）；需 updater 签名私钥'] },
  },
  'installer:build': {
    desc: '构建二游风格原生安装界面（固定版本 Tauri 模板）',
    cmd: ['node', 'scripts/maintenance/build-game-installer.js'],
    docs: 'docs/guides/desktop/game-installer.md',
    run: { nature: ['writes-release'], machine: ['windows', 'windows-toolchain'], switches: { '--preview': ['writes-product'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-game-installer.js:75-106', unknown: ['capture 模式隐藏启动界面截屏的完整生命周期未逐行核实'] },
  },
  'installer:preview': {
    desc: '编译安全界面预览（不安装、不提权；--page=welcome|directory|install|finish|maintenance）',
    cmd: ['node', 'scripts/maintenance/build-game-installer.js', '--preview'],
    docs: 'docs/guides/desktop/game-installer.md',
    run: { nature: ['writes-product'], machine: ['windows', 'windows-toolchain'], switches: { '--capture': ['writes-product'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-game-installer.js:122-124', unknown: [] },
  },
  'data:build': {
    desc: '聚合场景分片 -> scenes.json（热门角色见 popular:build）',
    cmd: ['node', 'scripts/maintenance/build-scenes.js'],
    docs: 'docs/maintenance.md#文件职责',
    run: { nature: ['writes-product', 'writes-source'], machine: ['node'], switches: { '--check': ['self-heal-missing', 'guard'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-scenes.js:15-42', unknown: [], notes: ['默认构建写聚合并计算 DATA_VERSION，客户端由 Vite virtual:data-version 注入，不改写 sceneStore.ts；--check 不写版本：产物缺失自愈重建（fresh clone，:15-22），齐全但与源不一致报错退出 1（:24-27）'] },
  },
  'popular:build': {
    desc: '聚合热门角色分片 -> popular-characters.json',
    cmd: ['node', 'scripts/maintenance/build-popular.js'],
    docs: 'docs/maintenance.md#文件职责',
    run: { nature: ['writes-product', 'writes-source'], machine: ['node'], switches: { '--check': ['self-heal-missing', 'guard'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-popular.js:12-37', unknown: [], notes: ['默认构建计算 DATA_VERSION，客户端由 Vite virtual:data-version 注入，不改写 sceneStore.ts；--check 不写版本：产物缺失自愈重建（fresh clone，:14-17），齐全但与源不一致报错退出 1（:18-21）'] },
  },
  'popular:split': {
    desc: 'popular→分片（仅写分片文件，不重建聚合；如需重建用 popular:import）',
    cmd: ['node', 'scripts/maintenance/split-popular.js', '--write'],
    docs: 'docs/maintenance.md',
    run: { nature: ['guard'], machine: ['node'], switches: { '--write': ['writes-source'] }, resume: 'idempotent', evidence: 'scripts/maintenance/split-popular.js:4-6', unknown: [], notes: ['缺 --write 直接拒绝退出 1；注册命令已固定 --write'] },
  },
  'popular:import': {
    desc: 'popular→分片+重建聚合（popular:split 超集，从聚合文件导入；改分片用 build）',
    cmd: ['npm', 'run', 'popular:import'],
    docs: 'docs/maintenance.md',
    run: { nature: ['writes-source', 'writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.popular:import（split-popular --write && build-popular）', unknown: [], notes: ['从聚合反向覆盖分片，先核对 diff'] },
  },
  'blueprints:build': {
    desc: '聚合场景蓝图分片 -> scene-blueprints.json',
    cmd: ['node', 'scripts/maintenance/build-blueprints.js'],
    docs: 'docs/maintenance.md#文件职责',
    run: { nature: ['writes-product', 'writes-source'], machine: ['node'], switches: { '--check': ['self-heal-missing', 'guard'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-blueprints.js:24-49', unknown: [], notes: ['默认构建计算 DATA_VERSION，客户端由 Vite virtual:data-version 注入，不改写 sceneStore.ts；--check 不写版本：产物缺失自愈重建（:26-29），齐全但与源不一致报错退出 1（:30-33）'] },
  },
  'blueprints:split': {
    desc: 'blueprints→分片（仅写分片文件，不重建聚合；如需重建用 blueprints:import）',
    cmd: ['node', 'scripts/maintenance/split-blueprints.js', '--write'],
    docs: 'docs/maintenance.md',
    run: { nature: ['guard'], machine: ['node'], switches: { '--write': ['writes-source'] }, resume: 'idempotent', evidence: 'scripts/maintenance/split-blueprints.js:11-13', unknown: [] },
  },
  'blueprints:import': {
    desc: 'blueprints→分片+重建聚合（blueprints:split 超集，从聚合文件导入；改分片用 build）',
    cmd: ['npm', 'run', 'blueprints:import'],
    docs: 'docs/maintenance.md',
    run: { nature: ['writes-source', 'writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.blueprints:import（split-blueprints --write && build-blueprints）', unknown: [] },
  },
  'data:import': {
    desc: 'scenes.json -> 分片 + 重建聚合（覆盖写入）',
    cmd: ['npm', 'run', 'scenes:import'],
    docs: 'docs/maintenance.md',
    run: { nature: ['writes-source', 'writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.scenes:import（split-scenes --write && build-scenes）', unknown: [], notes: ['writeSceneShards 按 ID 排序重切全部分组，中间插入/退役会移动后续批次条目（计划 006 D5）'] },
  },
  'data:normalize': {
    desc: '分类评级 + 规范标签 + 校验',
    cmd: ['npm', 'run', 'scenes:normalize'],
    docs: 'package.json',
    run: { nature: ['writes-source'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.scenes:normalize（classify-scene-ratings --write && optimize-scenes --write && validate-scenes）', unknown: [], notes: ['末段 validate-scenes 只读；分级脚本只维护分级元数据不改写 negative；定稿保护拦截受保护字段'] },
  },
  'data:validate': {
    desc: '内容契约 + DATA_VERSION 校验',
    cmd: ['node', 'scripts/maintenance/validate-content-contracts.js'],
    docs: 'docs/maintenance.md',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/validate-content-contracts.js:15', unknown: [] },
  },
  'content:sync': {
    desc: '统一校验人物/服装/场景，修正清单计数并构建聚合（默认只读预览）',
    cmd: ['node', 'scripts/maintenance/sync-content.js'],
    docs: 'docs/guides/characters/character-onboarding-workflow.md',
    opts: '[--apply] [--root=目录]；不登记或补齐角色参考图',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--apply': ['writes-source', 'writes-product'] }, resume: 'idempotent', evidence: 'scripts/maintenance/sync-content.ts', unknown: [], notes: ['不调用模型、不安装、不发布；不读取或写入参考库'] },
  },
  'reference:build': {
    desc: '从每人物参考分片构建兼容 standards/view 聚合',
    cmd: ['node', 'scripts/maintenance/build-references.js'],
    docs: 'docs/workflow.md',
    opts: '[--check]；check 仅在产物缺失时自愈，已有陈旧产物报错',
    run: { nature: ['writes-product'], machine: ['node'], switches: { '--check': ['read-only', 'self-heal-missing'] }, resume: 'idempotent', evidence: 'scripts/maintenance/build-references.ts', unknown: [], notes: ['data/references 为权威源；聚合不入 Git'] },
  },
  'reference:register': {
    desc: '从 popular 分片补登新人物/服装参考分片（pending 占位不制造断链）',
    cmd: ['node', 'scripts/maintenance/register-pending-reference-outfits.js'],
    docs: 'scripts/maintenance/register-pending-reference-outfits.js:1',
    opts: '[--dry-run] [--ids=a,b,c] 默认处理所有 popular 中 standards/view 缺失的服装；登记后仍需 reference:render 候选出图、人工验收及发布',
    run: { nature: ['writes-source', 'writes-product'], machine: ['node'], switches: { '--dry-run': ['preview'] }, resume: 'idempotent', evidence: 'scripts/maintenance/register-pending-reference-outfits.ts', unknown: [], notes: ['默认写每人物参考分片及兼容聚合；pending 不算已交付资产；按服装粒度增量登记'] },
  },
  'reference:render': {
    desc: '参考库四视角待审核候选出图（MiaoMiao v1.6，832x1216，默认并发3）',
    cmd: ['node', 'scripts/maintenance/render-all-outfits-references.js'],
    docs: 'docs/workflow.md#参考库',
    required: ['--output'],
    opts: '--output <候选目录> [--ids=a,b,c] [--root <数据根>] [--gateway <url>] [--concurrency <n>] [--dry-run] [--retry-unknown]',
    needs: '实际生成需 Anima gateway，默认 http://127.0.0.1:3000；预览无需网关',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: { '--dry-run': ['preview'], '--retry-unknown': ['external-model', 'writes-product'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/render-all-outfits-references.js:1; scripts/lib/generation-candidates.js:1', unknown: ['真实模型及画面审核未执行'], notes: ['只生成隔离候选，review 保持 pending；已知 job 恢复，未知提交需显式 retry-unknown；不回填活跃库'] },
  },
  'reference:audit': {
    desc: '纯视觉审核 4并发 (Gemini)',
    cmd: ['node', 'scripts/maintenance/pure-vision-audit.js'],
    docs: 'docs/workflow.md#参考库',
    opts: '[--force] [--keys char/outfit/pers,...] 强制重审指定项',
    run: { nature: ['external-model', 'writes-product'], machine: ['vision-api', 'node'], switches: { '--force': ['external-model', 'writes-product'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/pure-vision-audit.js:47-48', unknown: [], notes: ['视觉后端=本地 CLIProxyAPI 127.0.0.1:8317/v1（gemini-3.7-flash-high，回退 8000）'] },
  },
  'reference:repair': {
    desc: '定向修复未通过项（每项3次重渲染+重审）',
    cmd: ['node', 'scripts/maintenance/fine-tuned-repair.js'],
    docs: 'docs/workflow.md#参考库',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: {}, resume: 'checkpoint', evidence: 'scripts/maintenance/fine-tuned-repair.js:35,41,184', unknown: [] },
  },
  'reference:design': {
    desc: '三视图设计图批量渲染（增量默认跑 pending，--all 重跑）',
    cmd: ['node', 'scripts/maintenance/render-design-sheets.js'],
    docs: 'docs/workflow.md#参考库',
    opts: '[--chars=a,b] [--outfits=x,y] [--views=f,s,b] [--all] [--dry-run] [--limit=N]',
    needs: 'ComfyUI http://127.0.0.1:8188（--disable-smart-memory）',
    run: { nature: ['external-model', 'writes-product', 'writes-source'], machine: ['comfyui', 'node'], switches: { '--dry-run': ['preview'], '--limit': ['external-model'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/render-design-sheets.js:48,302-306,366', unknown: [], notes: ['出图后回填 view.json url（writes-source）'] },
  },
  ...(require('./lib/workflows-reference-candidates') as typeof import('./lib/workflows-reference-candidates')).referenceCandidateWorkflows,
  'showcase:generate': {
    desc: 'Anima 热门角色 × 蓝图候选出图',
    cmd: ['node', 'scripts/maintenance/generate-popular-showcase-anima11.js'],
    docs: 'docs/workflow.md#样张',
    required: ['--output'],
    opts: '--output <候选目录> --gateway http://127.0.0.1:3000 --keys popular:角色:蓝图 --model anima-miaomiao-v1.6 --concurrency 3',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: {}, resume: 'checkpoint', evidence: 'scripts/maintenance/generate-popular-showcase-anima11.js:16-18,44-49', unknown: [], notes: ['写仓库外 ../AI/Reviews/... 候选目录；assertIsolated 拒写公共 showcase'] },
  },
  'showcase:batch-miaomiao': {
    desc: 'MiaoMiao v1.6 场景待审核候选生成（832x1216/1216x832，默认并发3）',
    cmd: ['node', 'scripts/maintenance/generate-all-scenes-showcase-miaomiao.js'],
    docs: 'docs/workflow.md#样张',
    required: ['--output'],
    opts: '--output <候选目录> [--force] [--character <id>] [--limit <n>] [--root <数据根>] [--gateway <url>] [--concurrency <n>] [--dry-run] [--retry-unknown]',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: { '--force': ['external-model', 'writes-product'], '--dry-run': ['preview'], '--retry-unknown': ['external-model', 'writes-product'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/generate-all-scenes-showcase-miaomiao.js:1; scripts/lib/generation-candidates.js:1', unknown: ['真实模型及画面审核未执行'], notes: ['默认网关3000；隔离候选保持 pending，不自动发布；已知 job 可恢复'] },
  },
  'showcase:scene-candidates': {
    desc: '独立场景 MiaoMiao v1.6 候选生成（仅指定 ID，不发布）',
    cmd: ['node', 'scripts/maintenance/generate-scene-showcase-anima11.js', '--model', 'anima-miaomiao-v1.6'],
    docs: 'docs/workflow.md#样张',
    required: ['--output', '--ids'],
    opts: '--output <候选目录> --ids sc001,sc002 [--concurrency 1] [--dry-run]',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: { '--dry-run': ['preview'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/generate-scene-showcase-anima11.js:71-77,269-285', unknown: [] },
  },
  'showcase:fill-gaps': {
    docs: 'docs/workflow.md',
    desc: '只读样张清单并生成缺口待审核候选（MiaoMiao v1.6，沿用蓝图画幅，默认并发3）',
    cmd: ['node', 'scripts/maintenance/render-showcase-gaps.js'],
    required: ['--output'],
    opts: '--output <候选目录> [--manifest <源manifest>] [--only <角色id列表>] [--concurrency <n>] [--gateway <url>] [--root <数据根>] [--redo-mine] [--dry-run] [--retry-unknown]',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: { '--dry-run': ['preview'], '--retry-unknown': ['external-model', 'writes-product'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/render-showcase-gaps.js:1; scripts/lib/generation-candidates.js:1', unknown: ['真实模型及画面审核未执行'], notes: ['预览零写入，显式隔离候选目录；review 保持 pending，不回填活跃 manifest'] },
  },
  'showcase:audit': {
    required: ['--manifest', '--out'],
    desc: '批量审核 popular showcase (Gemini 4并发，rella)',
    cmd: ['node', 'scripts/maintenance/audit-showcase-rella.js'],
    docs: 'scripts/maintenance/audit-showcase-rella.js:1',
    run: { nature: ['external-model', 'writes-product'], machine: ['vision-api', 'node'], switches: {}, resume: 'checkpoint', evidence: 'scripts/maintenance/audit-showcase-rella.js:44-48', unknown: [] },
  },
  'showcase:audit:scene': {
    required: ['--manifest'],
    desc: '批量审核 scene showcase (Gemini 4并发，scene 版)',
    cmd: ['node', 'scripts/maintenance/audit-scene-showcase-run.js'],
    docs: 'scripts/maintenance/audit-scene-showcase-run.js:1',
    run: { nature: ['external-model', 'writes-product'], machine: ['vision-api', 'node'], switches: {}, resume: 'checkpoint', evidence: 'scripts/maintenance/audit-scene-showcase-run.js:93-113', unknown: [] },
  },
  'showcase:publish': {
    required: ['--from', '--source', '--target'],
    desc: '预览审核通过的样张发布（--apply 写入版本目录）',
    cmd: ['node', 'scripts/maintenance/publish-popular-showcase.js'],
    docs: 'docs/workflow.md#样张',
    run: { nature: ['preview'], machine: ['node', 'python-pillow'], switches: { '--apply': ['writes-release', 'writes-source'], '--force': ['delete', 'writes-release'] }, resume: 'idempotent', evidence: 'scripts/maintenance/publish-popular-showcase.js:9-12,24-27', unknown: [], notes: ['--apply 除新版本目录外还写仓库内 assets/characters/popular-<id>.png 立绘'] },
  },
  'showcase:batch': {
    desc: '统一批量调度（替代 8 个 run-batch-* 脚本）',
    cmd: ['node', 'scripts/maintenance/run-batch.js'],
    docs: 'scripts/maintenance/run-batch.js:1',
    opts: '--source popular|scenes --batch-size 10 --concurrency 3',
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'node'], switches: { '--dry-run': ['preview'], '--help': ['read-only'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/run-batch.js:35-54,165-166', unknown: ['实际副作用取决于被调度的 generate 脚本'] },
  },
  'showcase:full': {
    desc: '样张链路：generate -> audit -> 发布预览（--output / --source / --target 必填）',
    cmd: null,
    docs: 'docs/workflow.md#样张',
    steps: ['showcase:generate', 'showcase:audit', 'showcase:publish'],
    run: { nature: ['external-model', 'writes-product'], machine: ['gateway', 'vision-api', 'node', 'python-pillow'], switches: {}, resume: 'checkpoint', evidence: 'scripts/workflow.js:200-205; scripts/lib/workflow-runner.js:37-53', unknown: [], notes: ['复合：生成与审核实际执行，发布步仅预览（--apply 被 plan() 参数白名单拒绝）'] },
  },
  'check:quick': {
    desc: '并行质量门 npm run check（注册项全跑；与 gate:quick 区别：本命令全量并行，gate:quick 按改动面积只跑相关）',
    cmd: ['npm', 'run', 'check'],
    docs: 'AGENTS.md#实施与交付',
    run: { nature: ['read-only', 'self-heal-missing'], machine: ['node'], switches: { '--list': ['read-only'], '--all': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/run-check-parallel.js:22-57', unknown: [], notes: ['所有步骤为 --check/validate；失败后停止派发，--all 收集全貌；例外：fresh clone 产物缺失时 ensureAll 落盘自愈'] },
  },
  'gate:quick': {
    desc: '日常按 Git 改动选相关前端、样式、Node/Rust 和常规 E2E；显式 ui|style|rust|data|all 选择领域',
    cmd: ['node', 'scripts/maintenance/gate-quick.js'],
    opts: '[ui|style|rust|data|all] [--base HEAD|SHA] [--verbose] [--all]；直接 gate-quick.js --plan 输出选测 JSON',
    docs: 'docs/workflow.md',
    run: { nature: ['guard', 'self-heal-missing', 'isolated-fixture', 'writes-product'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/gate-quick.ts', unknown: ['实际范围由 Git 变更或位置参数决定；Rust 检查需要既有工具链，首次可能下载锁定 crate'], notes: ['npm test / npm run validate 同一入口；Rust源码/Cargo/隔离夹具变更只派发rust:check；自动 UI 按 Vitest 导入图选相关测试，纯style不跑类型与单测；已登记工具/CI消费者定向，依赖及未知影响面升级full；文档只查链接；CI用AICS_HYGIENE_BASE_REF，--base可覆盖；直接脚本--plan只读输出范围与clean checkout前置条件'] },
  },
  'gate:full': {
    desc: '全量门禁：check + Rust + 前端覆盖率 + unit + contract + tooling + release + 打包预算（横切重构/未知影响面）',
    cmd: ['node', 'scripts/maintenance/gate-quick.js', 'full'],
    docs: 'docs/workflow.md',
    run: { nature: ['read-only', 'self-heal-missing', 'writes-product'], machine: ['node', 'build-present'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/gate-quick.ts; scripts/maintenance/run-check-parallel.ts', unknown: ['需要 Rust 工具链；首次可能下载锁定 crate'], notes: ['显式full包含现行Rust后端fmt/Clippy/隔离行为检查，不含设备或真实模型；typecheck:app/typecheck 已包含在 check 编排内，不单独重复执行；末步执行 npm run build:web:run，复用 check 阶段已准备的 runtime（vite+预算+预压）'] },
  },
  'check:full': {
    desc: '显式全量，与 gate:full / validate:all 相同',
    cmd: ['npm', 'run', 'validate:all'],
    docs: 'AGENTS.md',
    run: { nature: ['read-only', 'self-heal-missing', 'writes-product'], machine: ['node', 'build-present'], switches: {}, resume: 'na', evidence: 'package.json scripts.validate:all', unknown: ['需要 Rust 工具链'], notes: ['与 gate:full 同一执行入口；不包含浏览器、设备或真实模型'] },
  },
  'check:content': {
    desc: '仅内容契约 + DATA_VERSION',
    cmd: ['npm', 'run', 'test:content'],
    docs: 'scripts/maintenance/validate-content-contracts.js:1',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'package.json scripts.test:content', unknown: [] },
  },
  'build:web': {
    desc: '前端构建 + 预算 + 预压',
    cmd: ['npm', 'run', 'build'],
    docs: 'AGENTS.md#实施与交付',
    run: { nature: ['writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.build（vite build && check-bundle-budget && precompress）', unknown: [], notes: ['PRECOMPRESS_JOBS 默认 2，有效范围 1–4；仅并行文件压缩，保持 Brotli 11 / gzip 9、预算与产物检查'] },
  },
  'build:runtime': {
    desc: '严格检查并编译服务、网关、工具和浏览器脚本；复用未变产物',
    cmd: ['npm', 'run', 'build:runtime'],
    docs: 'package.json',
    run: { nature: ['writes-product'], machine: ['node'], switches: {}, resume: 'idempotent', evidence: 'package.json scripts.build:runtime', unknown: [] },
  },
  'deploy:desktop': {
    desc: '桌面增量部署（跳过构建）',
    cmd: ['deploy-desktop.bat', '-SkipBuild'],
    docs: 'docs/desktop-deployment.md',
    run: {
      nature: ['writes-source', 'writes-product', 'writes-release', 'delete', 'service'], machine: ['windows'],
      switches: { '-SkipBuild': ['writes-source', 'writes-product', 'writes-release', 'delete', 'service'], '-Cleanup': ['delete'], '-UseInstaller': ['writes-release', 'delete', 'service'], '-InstallerPath': ['writes-release'], '-QuietInstall': ['writes-release'], '-NoRestart': ['writes-release'], '-StartupRepair': ['writes-release', 'service'] }, resume: 'idempotent',
      evidence: 'deploy-desktop.bat:18,22; scripts/maintenance/deploy-desktop-quick.ps1:20-28,114-122,178-184,290-296; scripts/lib/workflow-runner.js:178-182',
      unknown: [],
      notes: [
        '-SkipBuild 只跳过 npm run build（ps1:114-122）；数据聚合仍每次重建并写 data 产物（ps1:178-184），随后清 WebView2 缓存、修剪陈旧 chunk、验证反推依赖并启动桌面端（ps1:213-225,264-296）。',
        'bat 固定附加 -Cleanup（清安装目录源端删除型残留）再转发其余开关（bat:18）；非管理员时经 UAC 透传全部参数重启自身，需用户点「是」（ps1:52-70）；runner 强制 Windows 且仅接受无值开关（workflow-runner.js:178-182）。',
        '开关标签描述可能副作用，不抵消默认标签：-UseInstaller 改跑 runtime/desktop-updates 最新 *-setup.exe（前置：先 package:tauri 产出安装包，缺失退出 1；跳过本地构建及数据刷新，ps1:106,157-169）；-QuietInstall 仅随 -UseInstaller 静默安装（ps1:72,163-164）；-NoRestart 结束不启动；-StartupRepair 仅修 1.6.0 文档/图标/快捷方式，与 -UseInstaller 互斥（ps1:43,76-103）；-InstallDir <路径> 只能直接运行 bat。数据刷新可能写 DATA_VERSION。',
        '本入口安装后通过原生接口预览、备份并合并包内内容快照；缺快照或冲突中止，不覆盖个人库文件。StartupRepair 不导入；新素材包可由配套原生助手导入人物，旧包不含内容（docs/desktop-deployment.md#数据改动如何到达桌面端）。',
        'NSIS 静默/交互安装结束后可能不再回写 [5/6][6/6]，装机后需自行核对安装目录哈希、清缓存与启动状态。',
      ],
    },
  },
  'deploy:desktop:full': {
    desc: '桌面完整部署（前端构建 + 复制 + 清缓存 + 验证 + 重启）',
    cmd: ['deploy-desktop.bat'],
    docs: 'docs/desktop-deployment.md',
    run: {
      nature: ['writes-source', 'writes-product', 'writes-release', 'delete', 'service'], machine: ['windows'],
      switches: { '-SkipBuild': ['writes-source', 'writes-product', 'writes-release', 'delete', 'service'], '-Cleanup': ['delete'], '-UseInstaller': ['writes-release', 'delete', 'service'], '-InstallerPath': ['writes-release'], '-QuietInstall': ['writes-release'], '-NoRestart': ['writes-release'], '-StartupRepair': ['writes-release', 'service'] }, resume: 'idempotent',
      evidence: 'deploy-desktop.bat:18,22; scripts/maintenance/deploy-desktop-quick.ps1:20-28,114-119,178-184,186-211,290-296',
      unknown: [],
      notes: [
        '默认完整增量：npm run build → 停应用 → 清残留 → 刷新数据产物并复制 → 清 WebView2 缓存 + 验证依赖 → 启动（ps1:113-296）；增量模式要求安装目录已存在（ps1:108-111）。',
        'bat 固定附加 -Cleanup 再转发其余开关（bat:18）；非管理员时经 UAC 透传全部参数重启自身，需用户点「是」（ps1:52-70）；runner 强制 Windows 且仅接受无值开关（workflow-runner.js:178-182）。',
        '开关标签描述可能副作用，不抵消默认标签：-UseInstaller 改跑 runtime/desktop-updates 最新 *-setup.exe（前置：先 package:tauri 产出安装包，缺失退出 1；跳过本地构建及数据刷新，ps1:106,157-169）；-QuietInstall 仅随 -UseInstaller 静默安装（ps1:72,163-164）；-NoRestart 结束不启动；-StartupRepair 仅修 1.6.0 文档/图标/快捷方式，与 -UseInstaller 互斥（ps1:43,76-103）；-InstallDir <路径> 只能直接运行 bat。数据刷新可能写 DATA_VERSION。',
        '本入口安装后通过原生接口预览、备份并合并包内内容快照；缺快照或冲突中止，不覆盖个人库文件。StartupRepair 不导入；新素材包可由配套原生助手导入人物，旧包不含内容（docs/desktop-deployment.md#数据改动如何到达桌面端）。',
        'NSIS 静默/交互安装结束后可能不再回写 [5/6][6/6]，装机后需自行核对安装目录哈希、清缓存与启动状态。',
      ],
    },
  },
  // ── check: 单项门禁（可单独跑或组合）──────────────────────────────
  'check:monolith': {
    desc: '500 行红线只降不升门禁（以 monolith-baseline.json 为准）',
    cmd: ['node', 'scripts/tests/test-monolith-budget.js'],
    docs: 'scripts/tests/test-monolith-budget.js:1',
    opts: '[--update-baseline] 重新生成基线（体量真降后用）',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: { '--update-baseline': ['writes-baseline'] }, resume: 'na', evidence: 'scripts/tests/test-monolith-budget.js:141-147', unknown: [] },
  },
  'check:contrast': {
    desc: '双主题全局与角色强调色对比度门禁（WCAG AA）',
    cmd: ['node', 'scripts/maintenance/check-contrast.js', '--check'],
    docs: 'AGENTS.md#质量红线',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/check-contrast.js:288', unknown: [] },
  },
  'check:animations': {
    desc: 'GPU 合成属性门禁（禁 left/top/width/height 补间）',
    cmd: ['npm', 'run', 'lint:animations', '--', '--check'],
    docs: 'AGENTS.md#质量红线',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/maintenance/lint-animations.js:207-220', unknown: [] },
  },
  'check:ref-urls': {
    desc: '参考库 URL 断链门禁（按当前索引，pending 不算已发布）',
    cmd: ['node', 'scripts/maintenance/check-ref-urls.js'],
    opts: '[--root <完整项目根>]；优先级 --root > AICS_DATA_ROOT > AICS_APP_ROOT > 仓库根；--help/--plan 零目标读取',
    docs: 'scripts/maintenance/check-ref-urls.js:1',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: { '--root': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/check-ref-urls.js:93', unknown: [], notes: ['URL 存在性检查与网关共用素材根解析；素材根缺失可用 AICS_REFERENCE_AUDIT_MODE=structure（仅结构，须注明）'] },
  },
  'check:pinned-scenes': {
    desc: '定稿场景字节级保护门禁（100 条手工定稿）',
    cmd: ['node', 'scripts/tests/test-pinned-scene-prompts.js'],
    docs: 'AGENTS.md#质量红线',
    run: { nature: ['read-only', 'guard', 'isolated-fixture'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/test-pinned-scene-prompts.js:17,35-53', unknown: [], notes: ['门禁本体只读；自带测试使用临时夹具'] },
  },
  'check:rewrite': {
    desc: '批量改写完整性门禁（覆盖率/模板签名/跨条目雷同）',
    cmd: ['node', 'scripts/tests/test-prompt-rewrite-integrity.js', '--check'],
    docs: 'AGENTS.md#质量红线',
    opts: '[--delivery <条目文件/快照目录>] [--baseline <commit> | --baseline-file <编写前快照>] [--character <ID,...>] [--ids <ID,...>] [--sfw] [--compiled-out <双引擎输入JSON>] [--root <项目目录>] [--targeted]',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: { '--compiled-out':['writes-product'] }, resume: 'na', evidence: 'scripts/tests/test-prompt-rewrite-integrity.ts', unknown: [], notes: ['默认基线 HEAD，优先读取该提交的 data/catalog；迁移前提交才读旧分片。支持工作库导出的编写前快照；编译仅输出文本，不调用模型。'] },
  },
  'check:popular': {
    desc: '热门角色与提示词契约',
    cmd: ['node', 'scripts/tests/test-popular-content.js'],
    docs: 'scripts/tests/test-popular-content.js:1',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/test-popular-content.js:933-945', unknown: [] },
  },
  'check:frontend': {
    desc: '前端单测（vitest，stores/utils/composables 主战场）',
    cmd: ['npm', 'run', 'test:frontend'],
    docs: 'vitest.config.ts',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'na', evidence: 'package.json scripts.test:frontend', unknown: [] },
  },
  'check:style-debt': {
    desc: '样式债聚合门禁（style-debt + style-literals + contrast + colors + animations）',
    cmd: ['npm', 'run', 'test:style-debt'],
    docs: 'package.json',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'package.json scripts.test:style-debt', unknown: [] },
  },
  'check:bundle': {
    desc: '打包预算门禁（路由与依赖闭包，build:web 隐含）',
    cmd: ['node', 'scripts/maintenance/check-bundle-budget.js'],
    docs: 'AGENTS.md#实施与交付',
    run: { nature: ['read-only', 'guard'], machine: ['node', 'build-present'], switches: { '--json': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/check-bundle-budget.ts', unknown: [], notes: ['旧预算维持阻断；入口+匹配路由链JS并集仅报告，未知映射不计为零'] },
  },
  // ── backup / runtime: 磁盘债治理 ────────────────────────────────
  'backup:git': {
    desc: 'git bundle 本地第二副本（v2 增量链：锚点×2 + 增量×10）',
    cmd: ['node', 'scripts/maintenance/git-bundle-backup.js'],
    docs: 'scripts/maintenance/git-bundle-backup.js:1',
    opts: '[--keep N] 增量保留份数（默认 10）',
    run: { nature: ['writes-product', 'delete'], machine: ['node'], switches: {}, resume: 'checkpoint', evidence: 'scripts/maintenance/git-bundle-backup.js:61-129', unknown: [], notes: ['清理超量旧 bundle；不能替代 push/异地副本'] },
  },
  'runtime:clean': {
    desc: '实验孤儿目录清理（dry-run 默认、白名单保护、30 天 mtime 门槛）',
    cmd: ['node', 'scripts/maintenance/clean-runtime-experiments.js'],
    docs: 'scripts/maintenance/clean-runtime-experiments.js:1',
    opts: '[--prune] 真删  [--days N] 改门槛',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--prune': ['delete'] }, resume: 'idempotent', evidence: 'scripts/maintenance/clean-runtime-experiments.js:31-43,121-143', unknown: [], notes: ['--prune 仅删已收编实验目录（KNOWN_EXPERIMENTS/tmp-*）且超 --days（默认 30）；白名单与未识别目录永不删'] },
  },
  'comfy:start': {
    desc: '启动本机 ComfyUI（AI 工作区下的 Windows venv 布局）',
    cmd: ['powershell', '-ExecutionPolicy', 'Bypass', '-File', 'scripts/maintenance/start-comfyui.ps1'],
    docs: 'scripts/maintenance/start-comfyui.ps1:1',
    needs: 'AI 工作区下 ComfyUI/main.py、ComfyUI/venv/Scripts/python.exe 已准备；所需权重另验',
    opts: '已安装 SageAttention 且 CUDA 可用时默认启用；AICS_COMFY_USE_SAGE_ATTENTION=0 可关闭，缺依赖沿用 PyTorch；保留 [-UseSageAttention] 显式开关',
    run: { nature: ['service'], machine: ['windows'], switches: { '-UseSageAttention': ['service'] }, resume: 'na', evidence: 'scripts/maintenance/start-comfyui.ps1:1', unknown: [] },
  },
  'voice:service': {
    desc: '查看本机语音状态；显式 -Action Start/Stop 管理当前引擎',
    cmd: ['powershell.exe', '-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-File', 'scripts/lib/managed-voice.ps1'],
    required: ['-AIWorkspaceRoot', '-RuntimeRoot', '-TtsHost'],
    opts: '-AIWorkspaceRoot <AI目录> -RuntimeRoot <运行目录> -TtsHost <本机地址> [-Engine voxcpm2|gpt-sovits] [-Action Status|Start|Stop]',
    docs: 'docs/workflow.md',
    needs: 'VoxCPM2 已有 Python 环境、基座与角色 LoRA；runtime/config.json 保存 voices。不会下载模型。',
    run: { nature: ['read-only'], machine: ['windows'], switches: { '-Action': ['service'], '-Engine': ['read-only'] }, resume: 'na',
      evidence: 'scripts/lib/managed-voice.ps1; tools/voxcpm-server.py', unknown: ['真实角色发音与当时可用显存需另验'],
      notes: ['默认仅状态探测；Start 加载本机权重并写 PID/日志，Stop 释放本应用的 VoxCPM2。GPT 复用已有 Voice 启停脚本。'] },
  },
  // ── test: 套件入口 ────────────────────────────────────────────────
  'check:domain-types': {
    desc: '检查公共类型、结果快照与入册用例的间接依赖，报告类型边、运行候选边及未知导入',
    cmd: ['node', 'scripts/tests/test-domain-type-boundaries.js'],
    docs: 'docs/engineering-contracts.md#重构期间的任务与持久化边界',
    run: { nature: ['read-only', 'guard'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/lib/domain-type-boundaries.ts; scripts/tests/test-domain-type-boundaries-fixtures.ts', unknown: [] },
  },
  'test:contract': {
    desc: '契约测试套件（内容/接口/热门/Anima 等聚合）',
    cmd: ['npm', 'run', 'test:contract'],
    docs: 'package.json',
    run: { nature: ['isolated-fixture', 'self-heal-missing'], machine: ['node'], switches: { '--all': ['read-only'], '--verbose': ['read-only'] }, resume: 'na', evidence: 'scripts/tests/contract-test-policy.ts; scripts/tests/run-quality-suite.ts:runContractSuite', unknown: [], notes: ['CONTRACT_TEST_JOBS 默认 2，仅审核过的隔离夹具并行，其余串行；设 1 保持原顺序；有效范围 1–4；失败停止派发并等待在途任务，--all 继续全部文件'] },
  },
  'test:optional': {
    desc: '按 Git 变更选择维护工具和发行套件；未知影响面运行全部专项',
    cmd: ['npm', 'run', 'test:optional'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture', 'self-heal-missing', 'writes-product'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/run-optional-test-lanes.ts', unknown: ['实际范围由 Git 变更决定'], notes: ['相关源码变更自动补专项，保留失败退出码'] },
  },
  'test:tooling': {
    desc: '维护CLI、构建器和扫描器夹具专项', cmd: ['npm', 'run', 'test:tooling'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/quality-test-inventory.ts', unknown: [] },
  },
  'test:release': {
    desc: '发行、安装、资源包和桌面ABI专项', cmd: ['npm', 'run', 'test:release'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture'], machine: ['node'], switches: {}, resume: 'na', evidence: 'scripts/tests/quality-test-inventory.ts', unknown: ['Windows分支按宿主执行'], notes: ['不执行真实安装或发布'] },
  },
  'gate:all': {
    desc: '显式全部库存，与 gate:full / validate:all 相同', cmd: ['npm', 'run', 'validate:all'], docs: 'docs/workflow.md#门禁与构建',
    run: { nature: ['isolated-fixture', 'self-heal-missing', 'writes-product'], machine: ['node', 'build-present'], switches: {}, resume: 'na', evidence: 'package.json scripts.validate:all', unknown: ['需要 Rust 工具链'], notes: ['包含维护及发行专项；不包含浏览器、设备和真实模型'] },
  },
  'test:e2e:critical': {
    desc: '关键 e2e 套件：主流程、双主题/设备、角色及办公机回归（用例数以执行结果为准）',
    cmd: ['npm', 'run', 'test:e2e:critical:run'],
    docs: 'package.json',
    needs: 'playwright 浏览器已安装（npx playwright install）；已有前端构建产物',
    run: { nature: ['isolated-fixture'], machine: ['node', 'playwright-browser', 'build-present'], switches: {}, resume: 'na', evidence: 'package.json scripts.test:e2e:critical:run', unknown: [], notes: ['注册入口为无 build 的 :run 脚本，复用已有 dist（npm 脚本 test:e2e:critical 才先 build）；生成链路用模拟上游；浏览器测试期间不得重建共享 dist'] },
  },
  'test:e2e:performance': {
    desc: '独立单 worker 绘图页冷/热进入与首次操作测量',
    cmd: ['npm', 'run', 'test:e2e:performance'],
    docs: 'docs/workflow.md',
    needs: '已完成 build；运行时不要并行构建或执行其他浏览器测试',
    run: { nature: ['isolated-fixture'], machine: ['node', 'playwright-browser', 'build-present'], switches: {}, resume: 'na', evidence: 'playwright.performance.config.ts:7', unknown: [] },
  },
  'character:onboard': {
    desc: '历史立绘/样张流水线（直接写资产）；不登记或生成参考图库',
    cmd: ['npm', 'run', 'character:onboard'],
    docs: 'docs/guides/characters/character-onboarding-workflow.md',
    run: { nature: ['writes-source', 'external-model', 'writes-product'], machine: ['gateway', 'node', 'python-pillow'], switches: { '--skip-render': ['writes-source'], '--deploy': ['writes-release'] }, resume: 'checkpoint', evidence: 'scripts/maintenance/workflow-onboard-popular-character.js:23-348', unknown: [], notes: ['不登记或生成角色参考图库；--skip-render 跳过样张出图；历史 --deploy 仍直连 deploy-desktop-quick.ps1 -NoRestart，现行桌面同步另用 deploy-desktop.bat'] },
  },
  'audit:coverage': {
    desc: '只读差额报告：热门服装→参考登记、角色→主题选择器覆盖差额（信息性，不作为门禁失败依据）',
    cmd: ['node', 'scripts/maintenance/report-content-coverage.js'],
    opts: '[--json] 机器可读输出；[--root <目录>] 指定隔离夹具根（默认仓库根）；[--character <规范ID>] [--outfit <角色内ID>] 筛选范围（outfit 须与 character 同用）',
    docs: 'docs/workflow.md',
    run: { nature: ['read-only'], machine: ['node'], switches: { '--json': ['read-only'], '--character': ['read-only'], '--outfit': ['read-only'] }, resume: 'na', evidence: 'scripts/maintenance/report-content-coverage.js:1', unknown: [], notes: ['结构错误（清单缺文件/重复 ID/批次数不符）退出 1；覆盖差额只报告恒退出 0，不自动登记/补图/改主题', '筛选数量按所选范围重算并输出 scope；结构检查仍为全库，素材存在性只核对所选范围；未知角色/服装或 outfit 缺 character 退出 2'] },
  },
};

const { main } = (require('./lib/workflow-runner') as typeof import('./lib/workflow-runner'));
if (require.main === module) process.exitCode = main(process.argv.slice(2), WORKFLOWS, ROOT);
export = { WORKFLOWS };
