const fs = require('node:fs');
const path = require('node:path');
const Module = require('node:module');
const ts = require('typescript');
const root = path.resolve(__dirname, '../../../..');
const fixture = path.resolve(process.argv[2]);
process.env.AICS_APP_ROOT = fixture;
process.env.AICS_DATA_ROOT = fixture;
process.env.AICS_ASSETS_ROOT = path.join(fixture, 'assets');
process.env.AI_WORKSPACE_ROOT = path.join(fixture, 'AI');
process.env.AICS_CHARACTER_REF_ROOT = path.join(fixture, 'absent-references');
delete process.env.AICS_REFERENCE_AUDIT_MODE;
const file = path.join(root, 'scripts/maintenance/validate-content-contracts.ts');
let source = fs.readFileSync(file, 'utf8');
source = source.replace('export = { validateContent:validateContent };', 'export = { main };');
const moduleInstance = new Module(file, module);
moduleInstance.filename = file;
moduleInstance.paths = Module._nodeModulePaths(path.dirname(file));
moduleInstance._compile(ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, file);
const issues = [];
const log = console.log;
const error = console.error;
console.log = () => {};
console.error = value => issues.push(...String(value).split('\n').map(line => line.replace(/^\s*-\s*/, '')));
moduleInstance.exports.main();
console.log = log;
console.error = error;
process.exitCode = 0;
process.stdout.write(JSON.stringify(issues));
